// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button__UI$IsenseiMonorepo from "./Button__UI.mjs";

function Index$Button1(Props) {
  return React.createElement("div", undefined, "Component Button");
}

var Button1 = {
  make: Index$Button1,
};

var btn = React.createElement("div", undefined, "Button");

var btn2 = React.createElement(Button__UI$IsenseiMonorepo.make, {});

export { Button1, btn, btn2 };
/* btn Not a pure module */
