// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as React$1 from "@headlessui/react";

function ThemeSwitch__UI(Props) {
  var match = React.useState(function () {
        return false;
      });
  var setEnabled = match[1];
  var enabled = match[0];
  return React.createElement("div", {
              className: "flex items-center space-x-4"
            }, React.createElement("svg", {
                  height: "32",
                  width: "32",
                  fill: "none"
                }, React.createElement("path", {
                      clipRule: "evenodd",
                      d: "M16 2a1.4 1.4 0 011.4 1.4v1.4a1.4 1.4 0 11-2.8 0V3.4A1.4 1.4 0 0116 2zM6.1 6.1a1.4 1.4 0 011.98 0l.99.99a1.4 1.4 0 11-1.98 1.98l-.99-.99a1.4 1.4 0 010-1.98zm19.8 0a1.4 1.4 0 010 1.98l-.99.99a1.4 1.4 0 01-1.98-1.98l.99-.99a1.4 1.4 0 011.98 0zM9 16a7 7 0 1114 0 7 7 0 01-14 0zm-7 0a1.4 1.4 0 011.4-1.4h1.4a1.4 1.4 0 110 2.8H3.4A1.4 1.4 0 012 16zm23.8 0a1.4 1.4 0 011.4-1.4h1.4a1.4 1.4 0 110 2.8h-1.4a1.4 1.4 0 01-1.4-1.4zm-2.87 6.93a1.4 1.4 0 011.98 0l.99.99a1.4 1.4 0 01-1.98 1.98l-.99-.99a1.4 1.4 0 010-1.98zm-15.84 0a1.4 1.4 0 011.98 1.98l-.99.99a1.4 1.4 0 01-1.98-1.98l.99-.99zM16 25.8a1.4 1.4 0 011.4 1.4v1.4a1.4 1.4 0 11-2.8 0v-1.4a1.4 1.4 0 011.4-1.4z",
                      fill: "url(#paint0_linear)",
                      fillRule: "evenodd"
                    }), React.createElement("defs", undefined, React.createElement("linearGradient", {
                          id: "paint0_linear",
                          gradientUnits: "userSpaceOnUse",
                          x1: "2",
                          x2: "30",
                          y1: "2",
                          y2: "30"
                        }, React.createElement("stop", {
                              stopColor: enabled ? "#d4d4d8" : "#FACC15"
                            }), React.createElement("stop", {
                              offset: "1",
                              stopColor: enabled ? "#d4d4d8" : "#FA9D16"
                            })))), React.createElement(React$1.Switch, {
                  checked: enabled,
                  onChange: (function (param) {
                      return Curry._1(setEnabled, (function (_prev) {
                                    return !_prev;
                                  }));
                    }),
                  className: "inline-flex items-center px-0.5 rounded-full w-18 h-9 " + (
                    enabled ? "justify-end" : ""
                  ) + " " + (
                    enabled ? "backgroundColor: #000" : "backgroundColor: #60D360"
                  ),
                  children: (function (param) {
                      return React.createElement(React.Fragment, undefined, React.createElement("span", {
                                      className: "sr-only"
                                    }, "Enable dark mode"));
                    })
                }), React.createElement("svg", {
                  height: "24",
                  width: "24",
                  fill: "none"
                }, React.createElement("path", {
                      clipRule: "evenodd",
                      d: "M9.353 2.939a1 1 0 01.22 1.08 8 8 0 0010.408 10.408 1 1 0 011.301 1.3A10.003 10.003 0 0112 22C6.477 22 2 17.523 2 12c0-4.207 2.598-7.805 6.273-9.282a1 1 0 011.08.22z",
                      fill: enabled ? "#000" : "#d4d4d8",
                      fillRule: "evenodd"
                    })));
}

var make = ThemeSwitch__UI;

export {
  make ,
  
}
/* react Not a pure module */
