// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Tip__UI$IsenseiMonorepo from "./Tip__UI.mjs";
import * as Button__UI$IsenseiMonorepo from "./Button__UI.mjs";

function UI$Button1(Props) {
  return React.createElement("div", undefined, "Component Button");
}

var Button1 = {
  make: UI$Button1
};

var btn = React.createElement("div", undefined, "Button");

var btn2 = React.createElement(Button__UI$IsenseiMonorepo.make, {});

function tipGood(children) {
  return React.createElement(Tip__UI$IsenseiMonorepo.TipGood.make, {
              children: children
            });
}

function tipBad(children) {
  return React.createElement(Tip__UI$IsenseiMonorepo.TipBad.make, {
              children: children
            });
}

function tipCompat(children) {
  return React.createElement(Tip__UI$IsenseiMonorepo.TipCompat.make, {
              children: children
            });
}

function tipInfo(children) {
  return React.createElement(Tip__UI$IsenseiMonorepo.TipInfo.make, {
              children: children
            });
}

export {
  Button1 ,
  btn ,
  btn2 ,
  tipGood ,
  tipBad ,
  tipCompat ,
  tipInfo ,
  
}
/* btn Not a pure module */
