// Generated by ReScript, PLEASE EDIT WITH CARE

function toValue(scale) {
  if (scale === 50) {
    return 0.5;
  } else if (scale === 75) {
    return 0.75;
  } else if (scale === 90) {
    return 0.9;
  } else if (scale === 95) {
    return 0.95;
  } else if (scale === 100) {
    return 1.0;
  } else if (scale === 105) {
    return 1.05;
  } else if (scale === 110) {
    return 1.1;
  } else if (scale === 125) {
    return 1.25;
  } else if (scale === 150) {
    return 1.5;
  } else {
    return 0;
  }
}

export { toValue };
/* No side effect */
