// Generated by ReScript, PLEASE EDIT WITH CARE

function toValue(opacity) {
  if (opacity === 5) {
    return 0.05;
  } else if (opacity === 10) {
    return 0.1;
  } else if (opacity === 15) {
    return 0.15;
  } else if (opacity === 20) {
    return 0.2;
  } else if (opacity === 25) {
    return 0.25;
  } else if (opacity === 30) {
    return 0.3;
  } else if (opacity === 35) {
    return 0.35;
  } else if (opacity === 40) {
    return 0.4;
  } else if (opacity === 45) {
    return 0.45;
  } else if (opacity === 50) {
    return 0.5;
  } else if (opacity === 55) {
    return 0.55;
  } else if (opacity === 60) {
    return 0.6;
  } else if (opacity === 65) {
    return 0.65;
  } else if (opacity === 70) {
    return 0.7;
  } else if (opacity === 75) {
    return 0.75;
  } else if (opacity === 80) {
    return 0.8;
  } else if (opacity === 85) {
    return 0.85;
  } else if (opacity === 90) {
    return 0.9;
  } else if (opacity === 95) {
    return 0.95;
  } else if (opacity === 100) {
    return 1;
  } else {
    return 0;
  }
}

export { toValue };
/* No side effect */
