// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cypress$IsenseiMonorepo from "../../../../packages/bindings/cypress/Cypress.mjs";

Cypress$IsenseiMonorepo.context("Connectors", (function (param) {
        Cypress$IsenseiMonorepo.beforeEach(function (param) {
              cy.visit("https://example.cypress.io/commands/connectors", undefined);
              
            });
        Cypress$IsenseiMonorepo.it(".each() - iterate over an array of elements", (function (param) {
                cy.get(".connectors-each-ul>li", undefined).each(function (el, param, param$1) {
                      console.log(el);
                      
                    });
                
              }));
        Cypress$IsenseiMonorepo.it(".each() - iterate over an array of elements", (function (param) {
                cy.get(".connectors-each-ul>li", undefined).each(function (el, index, collection) {
                      console.log(el, index, collection);
                      
                    });
                
              }));
        Cypress$IsenseiMonorepo.it(".its() - get properties on the current subject", (function (param) {
                return Cypress$IsenseiMonorepo.shouldBeGtInt(cy.get(".connectors-its-ul>li", undefined).its("length", undefined), 2);
              }));
        Cypress$IsenseiMonorepo.it(".invoke() - invoke a function on the current subject", (function (param) {
                return Cypress$IsenseiMonorepo.shouldBeVisible(Cypress$IsenseiMonorepo.shouldBeHiddenP(cy.get(".connectors-div", undefined)).invoke(Cypress$IsenseiMonorepo.ChildrenOptions.make(undefined, undefined, undefined), "show"));
              }));
        Cypress$IsenseiMonorepo.describe(".then()", (function (param) {
                return Cypress$IsenseiMonorepo.it("invokes a callback function with the current subject", (function (param) {
                              cy.get(".connectors-list > li", undefined).then(function (lisRaw) {
                                    var el1 = lisRaw.get(0);
                                    var el2 = lisRaw.get(1);
                                    var el3 = lisRaw.get(2);
                                    Cypress$IsenseiMonorepo.expectWithDescription(lisRaw, "3 items").to.have.length(3);
                                    Cypress$IsenseiMonorepo.expectWithDescription(el1, "first item").to.have.text("Walk the dog");
                                    Cypress$IsenseiMonorepo.expectWithDescription(el2, "second item").to.have.text("Feed the cat");
                                    Cypress$IsenseiMonorepo.expectWithDescription(el3, "third item").to.have.text("Write JavaScript");
                                    
                                  });
                              
                            }));
              }));
        Cypress$IsenseiMonorepo.it("yields the returned value to the next command", (function (param) {
                cy.wrap(1).then(function (num) {
                        Cypress$IsenseiMonorepo.expect(num).equal(1);
                        return 2;
                      }).then(function (num) {
                      Cypress$IsenseiMonorepo.expect(num).equal(2);
                      
                    });
                
              }));
        Cypress$IsenseiMonorepo.it("yields the original subject without return", (function (param) {
                cy.wrap(1).then(function (num) {
                        Cypress$IsenseiMonorepo.expect(num).equal(1);
                        
                      }).then(function (num) {
                      Cypress$IsenseiMonorepo.expect(num).equal(1);
                      
                    });
                
              }));
        return Cypress$IsenseiMonorepo.it("yields the value yielded by the last Cypress command inside", (function (param) {
                      cy.wrap(1).then(function (num) {
                              Cypress$IsenseiMonorepo.expect(num).equal(1);
                              return cy.wrap(2);
                            }).then(function (num) {
                            Cypress$IsenseiMonorepo.expect(num).equal(2);
                            
                          });
                      
                    }));
      }));

export {
  
}
/*  Not a pure module */
