// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Cypress$IsenseiMonorepo from "../../../../packages/bindings/cypress/Cypress.bs.js";

Cypress$IsenseiMonorepo.context("Navigation", function (param) {
  Cypress$IsenseiMonorepo.beforeEach(function (param) {
    cy.visit("https://example.cypress.io", undefined);
    cy.get(".navbar-nav", undefined)
      .contains(undefined, "Commands", undefined)
      .click(undefined);
    cy.get(".dropdown-menu", undefined)
      .contains(undefined, "Navigation", undefined)
      .click(undefined);
  });
  Cypress$IsenseiMonorepo.it(
    'cy.go() - go back or forward in the browser"s history',
    function (param) {
      Cypress$IsenseiMonorepo.shouldInclude(
        cy.location("pathname", undefined),
        "navigation"
      );
      cy.go("back", undefined);
      Cypress$IsenseiMonorepo.shouldNotInclude(
        cy.location(
          "pathname",
          Cypress$IsenseiMonorepo.ChildrenOptions.make(
            undefined,
            undefined,
            undefined
          )
        ),
        "navigation"
      );
      cy.go(
        "forward",
        Cypress$IsenseiMonorepo.GoOptions.make(undefined, undefined, undefined)
      );
      Cypress$IsenseiMonorepo.shouldInclude(
        cy.location("pathname", undefined),
        "navigation"
      );
      cy.go("back", undefined);
      Cypress$IsenseiMonorepo.shouldNotInclude(
        cy.location("pathname", undefined),
        "navigation"
      );
      cy.go("forward", undefined);
      Cypress$IsenseiMonorepo.shouldInclude(
        cy.location("pathname", undefined),
        "navigation"
      );
      cy.location(undefined).then(function (locObj) {
        console.log(locObj);
      });
    }
  );
  Cypress$IsenseiMonorepo.it("cy.reload() - reload the page", function (param) {
    cy.reload(undefined);
    cy.reload(true, undefined);
  });
  return Cypress$IsenseiMonorepo.it(
    "cy.visit() - visit a remote url",
    function (param) {
      var beforeLoad = function (contentWindow) {
        console.log(contentWindow);
      };
      var onLoad = function (contentWindow) {
        console.log(contentWindow);
      };
      var visitOptions = Cypress$IsenseiMonorepo.VisitOptions.make(
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        beforeLoad,
        onLoad,
        undefined,
        undefined,
        5000,
        undefined
      );
      cy.visit("https://example.cypress.io/commands/navigation", visitOptions);
    }
  );
});

export {};
/*  Not a pure module */
