// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Js_dict from "rescript/lib/es6/js_dict.js";
import * as Css from "@emotion/css";
import * as Css_Colors$IsenseiMonorepo from "./Css_Colors.bs.js";
import * as Css_Js_Core$IsenseiMonorepo from "./Css_Js_Core.bs.js";

function renderRaw(param, css) {
  return Css.injectGlobal(css);
}

function injectRules(selector, rules) {
  return Css.injectGlobal(Js_dict.fromArray([[
                    selector,
                    rules
                  ]]));
}

function renderRules(param, selector, rules) {
  return Css.injectGlobal(Js_dict.fromArray([[
                    selector,
                    rules
                  ]]));
}

function makeKeyframes(frames) {
  return Css.keyframes(frames);
}

function renderKeyframes(param, frames) {
  return Css.keyframes(frames);
}

var include = Css_Js_Core$IsenseiMonorepo.Make({
      injectRaw: Css.injectGlobal,
      renderRaw: renderRaw,
      injectRules: injectRules,
      renderRules: renderRules,
      make: Css.css,
      mergeStyles: Css.cx,
      makeKeyframes: makeKeyframes,
      renderKeyframes: renderKeyframes
    });

var insertRule = include.insertRule;

function fontFace(fontFamily, src, fontStyle, fontWeight, fontDisplay, param) {
  insertRule(Css_Js_Core$IsenseiMonorepo.fontFace(fontFamily, src, fontStyle, fontWeight, fontDisplay, undefined));
  return fontFamily;
}

var Types = Css_Js_Core$IsenseiMonorepo.Types;

var Make = Css_Js_Core$IsenseiMonorepo.Make;

var toJson = Css_Js_Core$IsenseiMonorepo.toJson;

var important = Css_Js_Core$IsenseiMonorepo.important;

var label = Css_Js_Core$IsenseiMonorepo.label;

var Shadow = Css_Js_Core$IsenseiMonorepo.Shadow;

var unsafe = Css_Js_Core$IsenseiMonorepo.unsafe;

var alignContent = Css_Js_Core$IsenseiMonorepo.alignContent;

var alignItems = Css_Js_Core$IsenseiMonorepo.alignItems;

var alignSelf = Css_Js_Core$IsenseiMonorepo.alignSelf;

var animationDelay = Css_Js_Core$IsenseiMonorepo.animationDelay;

var animationDirection = Css_Js_Core$IsenseiMonorepo.animationDirection;

var animationDuration = Css_Js_Core$IsenseiMonorepo.animationDuration;

var animationFillMode = Css_Js_Core$IsenseiMonorepo.animationFillMode;

var animationIterationCount = Css_Js_Core$IsenseiMonorepo.animationIterationCount;

var animationPlayState = Css_Js_Core$IsenseiMonorepo.animationPlayState;

var animationTimingFunction = Css_Js_Core$IsenseiMonorepo.animationTimingFunction;

var backdropFilter = Css_Js_Core$IsenseiMonorepo.backdropFilter;

var backfaceVisibility = Css_Js_Core$IsenseiMonorepo.backfaceVisibility;

var backgroundAttachment = Css_Js_Core$IsenseiMonorepo.backgroundAttachment;

var backgroundColor = Css_Js_Core$IsenseiMonorepo.backgroundColor;

var backgroundClip = Css_Js_Core$IsenseiMonorepo.backgroundClip;

var backgroundImage = Css_Js_Core$IsenseiMonorepo.backgroundImage;

var backgroundOrigin = Css_Js_Core$IsenseiMonorepo.backgroundOrigin;

var backgroundPosition = Css_Js_Core$IsenseiMonorepo.backgroundPosition;

var backgroundPositions = Css_Js_Core$IsenseiMonorepo.backgroundPositions;

var backgroundPosition4 = Css_Js_Core$IsenseiMonorepo.backgroundPosition4;

var backgroundRepeat = Css_Js_Core$IsenseiMonorepo.backgroundRepeat;

var borderBottom = Css_Js_Core$IsenseiMonorepo.borderBottom;

var borderBottomColor = Css_Js_Core$IsenseiMonorepo.borderBottomColor;

var borderBottomLeftRadius = Css_Js_Core$IsenseiMonorepo.borderBottomLeftRadius;

var borderBottomRightRadius = Css_Js_Core$IsenseiMonorepo.borderBottomRightRadius;

var borderBottomStyle = Css_Js_Core$IsenseiMonorepo.borderBottomStyle;

var borderBottomWidth = Css_Js_Core$IsenseiMonorepo.borderBottomWidth;

var borderCollapse = Css_Js_Core$IsenseiMonorepo.borderCollapse;

var borderColor = Css_Js_Core$IsenseiMonorepo.borderColor;

var borderLeft = Css_Js_Core$IsenseiMonorepo.borderLeft;

var borderLeftColor = Css_Js_Core$IsenseiMonorepo.borderLeftColor;

var borderLeftStyle = Css_Js_Core$IsenseiMonorepo.borderLeftStyle;

var borderLeftWidth = Css_Js_Core$IsenseiMonorepo.borderLeftWidth;

var borderRight = Css_Js_Core$IsenseiMonorepo.borderRight;

var borderRightColor = Css_Js_Core$IsenseiMonorepo.borderRightColor;

var borderRightStyle = Css_Js_Core$IsenseiMonorepo.borderRightStyle;

var borderRightWidth = Css_Js_Core$IsenseiMonorepo.borderRightWidth;

var borderRadius = Css_Js_Core$IsenseiMonorepo.borderRadius;

var borderRadius4 = Css_Js_Core$IsenseiMonorepo.borderRadius4;

var borderSpacing = Css_Js_Core$IsenseiMonorepo.borderSpacing;

var borderStyle = Css_Js_Core$IsenseiMonorepo.borderStyle;

var borderTopColor = Css_Js_Core$IsenseiMonorepo.borderTopColor;

var borderTopLeftRadius = Css_Js_Core$IsenseiMonorepo.borderTopLeftRadius;

var borderTopRightRadius = Css_Js_Core$IsenseiMonorepo.borderTopRightRadius;

var borderTopStyle = Css_Js_Core$IsenseiMonorepo.borderTopStyle;

var borderTopWidth = Css_Js_Core$IsenseiMonorepo.borderTopWidth;

var borderWidth = Css_Js_Core$IsenseiMonorepo.borderWidth;

var bottom = Css_Js_Core$IsenseiMonorepo.bottom;

var boxSizing = Css_Js_Core$IsenseiMonorepo.boxSizing;

var boxShadow = Css_Js_Core$IsenseiMonorepo.boxShadow;

var boxShadows = Css_Js_Core$IsenseiMonorepo.boxShadows;

var clear = Css_Js_Core$IsenseiMonorepo.clear;

var clipPath = Css_Js_Core$IsenseiMonorepo.clipPath;

var color = Css_Js_Core$IsenseiMonorepo.color;

var columnCount = Css_Js_Core$IsenseiMonorepo.columnCount;

var contentRule = Css_Js_Core$IsenseiMonorepo.contentRule;

var contentRules = Css_Js_Core$IsenseiMonorepo.contentRules;

var counterIncrement = Css_Js_Core$IsenseiMonorepo.counterIncrement;

var countersIncrement = Css_Js_Core$IsenseiMonorepo.countersIncrement;

var counterReset = Css_Js_Core$IsenseiMonorepo.counterReset;

var countersReset = Css_Js_Core$IsenseiMonorepo.countersReset;

var counterSet = Css_Js_Core$IsenseiMonorepo.counterSet;

var countersSet = Css_Js_Core$IsenseiMonorepo.countersSet;

var cursor = Css_Js_Core$IsenseiMonorepo.cursor;

var direction = Css_Js_Core$IsenseiMonorepo.direction;

var display = Css_Js_Core$IsenseiMonorepo.display;

var flex = Css_Js_Core$IsenseiMonorepo.flex;

var flexBasis = Css_Js_Core$IsenseiMonorepo.flexBasis;

var flexDirection = Css_Js_Core$IsenseiMonorepo.flexDirection;

var flexGrow = Css_Js_Core$IsenseiMonorepo.flexGrow;

var flexShrink = Css_Js_Core$IsenseiMonorepo.flexShrink;

var flexWrap = Css_Js_Core$IsenseiMonorepo.flexWrap;

var $$float = Css_Js_Core$IsenseiMonorepo.$$float;

var fontFamily = Css_Js_Core$IsenseiMonorepo.fontFamily;

var fontFamilies = Css_Js_Core$IsenseiMonorepo.fontFamilies;

var fontSize = Css_Js_Core$IsenseiMonorepo.fontSize;

var fontStyle = Css_Js_Core$IsenseiMonorepo.fontStyle;

var fontVariant = Css_Js_Core$IsenseiMonorepo.fontVariant;

var fontWeight = Css_Js_Core$IsenseiMonorepo.fontWeight;

var gridArea = Css_Js_Core$IsenseiMonorepo.gridArea;

var gridArea2 = Css_Js_Core$IsenseiMonorepo.gridArea2;

var gridArea3 = Css_Js_Core$IsenseiMonorepo.gridArea3;

var gridArea4 = Css_Js_Core$IsenseiMonorepo.gridArea4;

var gridAutoFlow = Css_Js_Core$IsenseiMonorepo.gridAutoFlow;

var gridColumn = Css_Js_Core$IsenseiMonorepo.gridColumn;

var gridColumnEnd = Css_Js_Core$IsenseiMonorepo.gridColumnEnd;

var columnGap = Css_Js_Core$IsenseiMonorepo.columnGap;

var scrollBehavior = Css_Js_Core$IsenseiMonorepo.scrollBehavior;

var columnWidth = Css_Js_Core$IsenseiMonorepo.columnWidth;

var caretColor = Css_Js_Core$IsenseiMonorepo.caretColor;

var gridColumnGap = Css_Js_Core$IsenseiMonorepo.gridColumnGap;

var gridColumnStart = Css_Js_Core$IsenseiMonorepo.gridColumnStart;

var gap = Css_Js_Core$IsenseiMonorepo.gap;

var gap2 = Css_Js_Core$IsenseiMonorepo.gap2;

var gridGap = Css_Js_Core$IsenseiMonorepo.gridGap;

var gridRow = Css_Js_Core$IsenseiMonorepo.gridRow;

var gridRowEnd = Css_Js_Core$IsenseiMonorepo.gridRowEnd;

var gridRowGap = Css_Js_Core$IsenseiMonorepo.gridRowGap;

var rowGap = Css_Js_Core$IsenseiMonorepo.rowGap;

var gridRowStart = Css_Js_Core$IsenseiMonorepo.gridRowStart;

var gridTemplateAreas = Css_Js_Core$IsenseiMonorepo.gridTemplateAreas;

var height = Css_Js_Core$IsenseiMonorepo.height;

var justifyContent = Css_Js_Core$IsenseiMonorepo.justifyContent;

var justifyItems = Css_Js_Core$IsenseiMonorepo.justifyItems;

var justifySelf = Css_Js_Core$IsenseiMonorepo.justifySelf;

var left = Css_Js_Core$IsenseiMonorepo.left;

var letterSpacing = Css_Js_Core$IsenseiMonorepo.letterSpacing;

var lineHeight = Css_Js_Core$IsenseiMonorepo.lineHeight;

var listStyle = Css_Js_Core$IsenseiMonorepo.listStyle;

var listStyleImage = Css_Js_Core$IsenseiMonorepo.listStyleImage;

var listStyleType = Css_Js_Core$IsenseiMonorepo.listStyleType;

var listStylePosition = Css_Js_Core$IsenseiMonorepo.listStylePosition;

var margin = Css_Js_Core$IsenseiMonorepo.margin;

var margin2 = Css_Js_Core$IsenseiMonorepo.margin2;

var margin3 = Css_Js_Core$IsenseiMonorepo.margin3;

var margin4 = Css_Js_Core$IsenseiMonorepo.margin4;

var marginLeft = Css_Js_Core$IsenseiMonorepo.marginLeft;

var marginRight = Css_Js_Core$IsenseiMonorepo.marginRight;

var marginTop = Css_Js_Core$IsenseiMonorepo.marginTop;

var marginBottom = Css_Js_Core$IsenseiMonorepo.marginBottom;

var maxHeight = Css_Js_Core$IsenseiMonorepo.maxHeight;

var maxWidth = Css_Js_Core$IsenseiMonorepo.maxWidth;

var minHeight = Css_Js_Core$IsenseiMonorepo.minHeight;

var minWidth = Css_Js_Core$IsenseiMonorepo.minWidth;

var objectFit = Css_Js_Core$IsenseiMonorepo.objectFit;

var objectPosition = Css_Js_Core$IsenseiMonorepo.objectPosition;

var opacity = Css_Js_Core$IsenseiMonorepo.opacity;

var order = Css_Js_Core$IsenseiMonorepo.order;

var outline = Css_Js_Core$IsenseiMonorepo.outline;

var outlineColor = Css_Js_Core$IsenseiMonorepo.outlineColor;

var outlineOffset = Css_Js_Core$IsenseiMonorepo.outlineOffset;

var outlineStyle = Css_Js_Core$IsenseiMonorepo.outlineStyle;

var outlineWidth = Css_Js_Core$IsenseiMonorepo.outlineWidth;

var overflow = Css_Js_Core$IsenseiMonorepo.overflow;

var overflowX = Css_Js_Core$IsenseiMonorepo.overflowX;

var overflowY = Css_Js_Core$IsenseiMonorepo.overflowY;

var overflowWrap = Css_Js_Core$IsenseiMonorepo.overflowWrap;

var padding = Css_Js_Core$IsenseiMonorepo.padding;

var padding2 = Css_Js_Core$IsenseiMonorepo.padding2;

var padding3 = Css_Js_Core$IsenseiMonorepo.padding3;

var padding4 = Css_Js_Core$IsenseiMonorepo.padding4;

var paddingLeft = Css_Js_Core$IsenseiMonorepo.paddingLeft;

var paddingRight = Css_Js_Core$IsenseiMonorepo.paddingRight;

var paddingTop = Css_Js_Core$IsenseiMonorepo.paddingTop;

var paddingBottom = Css_Js_Core$IsenseiMonorepo.paddingBottom;

var perspective = Css_Js_Core$IsenseiMonorepo.perspective;

var perspectiveOrigin = Css_Js_Core$IsenseiMonorepo.perspectiveOrigin;

var pointerEvents = Css_Js_Core$IsenseiMonorepo.pointerEvents;

var position = Css_Js_Core$IsenseiMonorepo.position;

var resize = Css_Js_Core$IsenseiMonorepo.resize;

var right = Css_Js_Core$IsenseiMonorepo.right;

var tableLayout = Css_Js_Core$IsenseiMonorepo.tableLayout;

var textAlign = Css_Js_Core$IsenseiMonorepo.textAlign;

var textDecorationColor = Css_Js_Core$IsenseiMonorepo.textDecorationColor;

var textDecorationLine = Css_Js_Core$IsenseiMonorepo.textDecorationLine;

var textDecorationStyle = Css_Js_Core$IsenseiMonorepo.textDecorationStyle;

var textIndent = Css_Js_Core$IsenseiMonorepo.textIndent;

var textOverflow = Css_Js_Core$IsenseiMonorepo.textOverflow;

var textShadow = Css_Js_Core$IsenseiMonorepo.textShadow;

var textShadows = Css_Js_Core$IsenseiMonorepo.textShadows;

var textTransform = Css_Js_Core$IsenseiMonorepo.textTransform;

var top = Css_Js_Core$IsenseiMonorepo.top;

var transform = Css_Js_Core$IsenseiMonorepo.transform;

var transforms = Css_Js_Core$IsenseiMonorepo.transforms;

var transformOrigin = Css_Js_Core$IsenseiMonorepo.transformOrigin;

var transformOrigin3d = Css_Js_Core$IsenseiMonorepo.transformOrigin3d;

var transitionDelay = Css_Js_Core$IsenseiMonorepo.transitionDelay;

var transitionDuration = Css_Js_Core$IsenseiMonorepo.transitionDuration;

var transitionProperty = Css_Js_Core$IsenseiMonorepo.transitionProperty;

var transformStyle = Css_Js_Core$IsenseiMonorepo.transformStyle;

var transitionTimingFunction = Css_Js_Core$IsenseiMonorepo.transitionTimingFunction;

var userSelect = Css_Js_Core$IsenseiMonorepo.userSelect;

var verticalAlign = Css_Js_Core$IsenseiMonorepo.verticalAlign;

var visibility = Css_Js_Core$IsenseiMonorepo.visibility;

var width = Css_Js_Core$IsenseiMonorepo.width;

var whiteSpace = Css_Js_Core$IsenseiMonorepo.whiteSpace;

var wordBreak = Css_Js_Core$IsenseiMonorepo.wordBreak;

var wordSpacing = Css_Js_Core$IsenseiMonorepo.wordSpacing;

var wordWrap = Css_Js_Core$IsenseiMonorepo.wordWrap;

var zIndex = Css_Js_Core$IsenseiMonorepo.zIndex;

var selector = Css_Js_Core$IsenseiMonorepo.selector;

var media = Css_Js_Core$IsenseiMonorepo.media;

var active = Css_Js_Core$IsenseiMonorepo.active;

var checked = Css_Js_Core$IsenseiMonorepo.checked;

var $$default = Css_Js_Core$IsenseiMonorepo.$$default;

var defined = Css_Js_Core$IsenseiMonorepo.defined;

var disabled = Css_Js_Core$IsenseiMonorepo.disabled;

var empty = Css_Js_Core$IsenseiMonorepo.empty;

var enabled = Css_Js_Core$IsenseiMonorepo.enabled;

var first = Css_Js_Core$IsenseiMonorepo.first;

var firstChild = Css_Js_Core$IsenseiMonorepo.firstChild;

var firstOfType = Css_Js_Core$IsenseiMonorepo.firstOfType;

var focus = Css_Js_Core$IsenseiMonorepo.focus;

var focusVisible = Css_Js_Core$IsenseiMonorepo.focusVisible;

var focusWithin = Css_Js_Core$IsenseiMonorepo.focusWithin;

var host = Css_Js_Core$IsenseiMonorepo.host;

var hover = Css_Js_Core$IsenseiMonorepo.hover;

var indeterminate = Css_Js_Core$IsenseiMonorepo.indeterminate;

var inRange = Css_Js_Core$IsenseiMonorepo.inRange;

var invalid = Css_Js_Core$IsenseiMonorepo.invalid;

var lang = Css_Js_Core$IsenseiMonorepo.lang;

var lastChild = Css_Js_Core$IsenseiMonorepo.lastChild;

var lastOfType = Css_Js_Core$IsenseiMonorepo.lastOfType;

var link = Css_Js_Core$IsenseiMonorepo.link;

var not__ = Css_Js_Core$IsenseiMonorepo.not__;

var Nth = Css_Js_Core$IsenseiMonorepo.Nth;

var nthChild = Css_Js_Core$IsenseiMonorepo.nthChild;

var nthLastChild = Css_Js_Core$IsenseiMonorepo.nthLastChild;

var nthLastOfType = Css_Js_Core$IsenseiMonorepo.nthLastOfType;

var nthOfType = Css_Js_Core$IsenseiMonorepo.nthOfType;

var onlyChild = Css_Js_Core$IsenseiMonorepo.onlyChild;

var onlyOfType = Css_Js_Core$IsenseiMonorepo.onlyOfType;

var optional = Css_Js_Core$IsenseiMonorepo.optional;

var outOfRange = Css_Js_Core$IsenseiMonorepo.outOfRange;

var readOnly = Css_Js_Core$IsenseiMonorepo.readOnly;

var readWrite = Css_Js_Core$IsenseiMonorepo.readWrite;

var required = Css_Js_Core$IsenseiMonorepo.required;

var root = Css_Js_Core$IsenseiMonorepo.root;

var scope = Css_Js_Core$IsenseiMonorepo.scope;

var target = Css_Js_Core$IsenseiMonorepo.target;

var valid = Css_Js_Core$IsenseiMonorepo.valid;

var visited = Css_Js_Core$IsenseiMonorepo.visited;

var after = Css_Js_Core$IsenseiMonorepo.after;

var before = Css_Js_Core$IsenseiMonorepo.before;

var firstLetter = Css_Js_Core$IsenseiMonorepo.firstLetter;

var firstLine = Css_Js_Core$IsenseiMonorepo.firstLine;

var placeholder = Css_Js_Core$IsenseiMonorepo.placeholder;

var selection = Css_Js_Core$IsenseiMonorepo.selection;

var child = Css_Js_Core$IsenseiMonorepo.child;

var children = Css_Js_Core$IsenseiMonorepo.children;

var directSibling = Css_Js_Core$IsenseiMonorepo.directSibling;

var siblings = Css_Js_Core$IsenseiMonorepo.siblings;

var anyLink = Css_Js_Core$IsenseiMonorepo.anyLink;

var initial = Css_Js_Core$IsenseiMonorepo.initial;

var inherit_ = Css_Js_Core$IsenseiMonorepo.inherit_;

var unset = Css_Js_Core$IsenseiMonorepo.unset;

var $$var = Css_Js_Core$IsenseiMonorepo.$$var;

var varDefault = Css_Js_Core$IsenseiMonorepo.varDefault;

var auto = Css_Js_Core$IsenseiMonorepo.auto;

var none = Css_Js_Core$IsenseiMonorepo.none;

var text = Css_Js_Core$IsenseiMonorepo.text;

var pct = Css_Js_Core$IsenseiMonorepo.pct;

var ch = Css_Js_Core$IsenseiMonorepo.ch;

var cm = Css_Js_Core$IsenseiMonorepo.cm;

var em = Css_Js_Core$IsenseiMonorepo.em;

var ex = Css_Js_Core$IsenseiMonorepo.ex;

var mm = Css_Js_Core$IsenseiMonorepo.mm;

var pt = Css_Js_Core$IsenseiMonorepo.pt;

var px = Css_Js_Core$IsenseiMonorepo.px;

var pxFloat = Css_Js_Core$IsenseiMonorepo.pxFloat;

var rem = Css_Js_Core$IsenseiMonorepo.rem;

var vh = Css_Js_Core$IsenseiMonorepo.vh;

var vmin = Css_Js_Core$IsenseiMonorepo.vmin;

var vmax = Css_Js_Core$IsenseiMonorepo.vmax;

var zero = Css_Js_Core$IsenseiMonorepo.zero;

var deg = Css_Js_Core$IsenseiMonorepo.deg;

var rad = Css_Js_Core$IsenseiMonorepo.rad;

var grad = Css_Js_Core$IsenseiMonorepo.grad;

var turn = Css_Js_Core$IsenseiMonorepo.turn;

var ltr = Css_Js_Core$IsenseiMonorepo.ltr;

var rtl = Css_Js_Core$IsenseiMonorepo.rtl;

var absolute = Css_Js_Core$IsenseiMonorepo.absolute;

var relative = Css_Js_Core$IsenseiMonorepo.relative;

var $$static = Css_Js_Core$IsenseiMonorepo.$$static;

var fixed = Css_Js_Core$IsenseiMonorepo.fixed;

var sticky = Css_Js_Core$IsenseiMonorepo.sticky;

var horizontal = Css_Js_Core$IsenseiMonorepo.horizontal;

var vertical = Css_Js_Core$IsenseiMonorepo.vertical;

var smallCaps = Css_Js_Core$IsenseiMonorepo.smallCaps;

var italic = Css_Js_Core$IsenseiMonorepo.italic;

var oblique = Css_Js_Core$IsenseiMonorepo.oblique;

var hidden = Css_Js_Core$IsenseiMonorepo.hidden;

var visible = Css_Js_Core$IsenseiMonorepo.visible;

var scroll = Css_Js_Core$IsenseiMonorepo.scroll;

var rgb = Css_Js_Core$IsenseiMonorepo.rgb;

var rgba = Css_Js_Core$IsenseiMonorepo.rgba;

var hsl = Css_Js_Core$IsenseiMonorepo.hsl;

var hsla = Css_Js_Core$IsenseiMonorepo.hsla;

var hex = Css_Js_Core$IsenseiMonorepo.hex;

var currentColor = Css_Js_Core$IsenseiMonorepo.currentColor;

var local = Css_Js_Core$IsenseiMonorepo.local;

var paddingBox = Css_Js_Core$IsenseiMonorepo.paddingBox;

var borderBox = Css_Js_Core$IsenseiMonorepo.borderBox;

var contentBox = Css_Js_Core$IsenseiMonorepo.contentBox;

var noRepeat = Css_Js_Core$IsenseiMonorepo.noRepeat;

var space = Css_Js_Core$IsenseiMonorepo.space;

var repeat = Css_Js_Core$IsenseiMonorepo.repeat;

var minmax = Css_Js_Core$IsenseiMonorepo.minmax;

var repeatX = Css_Js_Core$IsenseiMonorepo.repeatX;

var repeatY = Css_Js_Core$IsenseiMonorepo.repeatY;

var contain = Css_Js_Core$IsenseiMonorepo.contain;

var cover = Css_Js_Core$IsenseiMonorepo.cover;

var row = Css_Js_Core$IsenseiMonorepo.row;

var rowReverse = Css_Js_Core$IsenseiMonorepo.rowReverse;

var column = Css_Js_Core$IsenseiMonorepo.column;

var columnReverse = Css_Js_Core$IsenseiMonorepo.columnReverse;

var wrap = Css_Js_Core$IsenseiMonorepo.wrap;

var nowrap = Css_Js_Core$IsenseiMonorepo.nowrap;

var wrapReverse = Css_Js_Core$IsenseiMonorepo.wrapReverse;

var inline = Css_Js_Core$IsenseiMonorepo.inline;

var block = Css_Js_Core$IsenseiMonorepo.block;

var contents = Css_Js_Core$IsenseiMonorepo.contents;

var flexBox = Css_Js_Core$IsenseiMonorepo.flexBox;

var grid = Css_Js_Core$IsenseiMonorepo.grid;

var inlineBlock = Css_Js_Core$IsenseiMonorepo.inlineBlock;

var inlineFlex = Css_Js_Core$IsenseiMonorepo.inlineFlex;

var inlineGrid = Css_Js_Core$IsenseiMonorepo.inlineGrid;

var inlineTable = Css_Js_Core$IsenseiMonorepo.inlineTable;

var listItem = Css_Js_Core$IsenseiMonorepo.listItem;

var runIn = Css_Js_Core$IsenseiMonorepo.runIn;

var table = Css_Js_Core$IsenseiMonorepo.table;

var tableCaption = Css_Js_Core$IsenseiMonorepo.tableCaption;

var tableColumnGroup = Css_Js_Core$IsenseiMonorepo.tableColumnGroup;

var tableHeaderGroup = Css_Js_Core$IsenseiMonorepo.tableHeaderGroup;

var tableFooterGroup = Css_Js_Core$IsenseiMonorepo.tableFooterGroup;

var tableRowGroup = Css_Js_Core$IsenseiMonorepo.tableRowGroup;

var tableCell = Css_Js_Core$IsenseiMonorepo.tableCell;

var tableColumn = Css_Js_Core$IsenseiMonorepo.tableColumn;

var tableRow = Css_Js_Core$IsenseiMonorepo.tableRow;

var flexStart = Css_Js_Core$IsenseiMonorepo.flexStart;

var flexEnd = Css_Js_Core$IsenseiMonorepo.flexEnd;

var center = Css_Js_Core$IsenseiMonorepo.center;

var stretch = Css_Js_Core$IsenseiMonorepo.stretch;

var spaceBetween = Css_Js_Core$IsenseiMonorepo.spaceBetween;

var spaceAround = Css_Js_Core$IsenseiMonorepo.spaceAround;

var spaceEvenly = Css_Js_Core$IsenseiMonorepo.spaceEvenly;

var baseline = Css_Js_Core$IsenseiMonorepo.baseline;

var forwards = Css_Js_Core$IsenseiMonorepo.forwards;

var backwards = Css_Js_Core$IsenseiMonorepo.backwards;

var both = Css_Js_Core$IsenseiMonorepo.both;

var infinite = Css_Js_Core$IsenseiMonorepo.infinite;

var count = Css_Js_Core$IsenseiMonorepo.count;

var paused = Css_Js_Core$IsenseiMonorepo.paused;

var running = Css_Js_Core$IsenseiMonorepo.running;

var inside = Css_Js_Core$IsenseiMonorepo.inside;

var outside = Css_Js_Core$IsenseiMonorepo.outside;

var solid = Css_Js_Core$IsenseiMonorepo.solid;

var dotted = Css_Js_Core$IsenseiMonorepo.dotted;

var dashed = Css_Js_Core$IsenseiMonorepo.dashed;

var underline = Css_Js_Core$IsenseiMonorepo.underline;

var overline = Css_Js_Core$IsenseiMonorepo.overline;

var lineThrough = Css_Js_Core$IsenseiMonorepo.lineThrough;

var clip = Css_Js_Core$IsenseiMonorepo.clip;

var ellipsis = Css_Js_Core$IsenseiMonorepo.ellipsis;

var wavy = Css_Js_Core$IsenseiMonorepo.wavy;

var $$double = Css_Js_Core$IsenseiMonorepo.$$double;

var uppercase = Css_Js_Core$IsenseiMonorepo.uppercase;

var lowercase = Css_Js_Core$IsenseiMonorepo.lowercase;

var capitalize = Css_Js_Core$IsenseiMonorepo.capitalize;

var sub = Css_Js_Core$IsenseiMonorepo.sub;

var $$super = Css_Js_Core$IsenseiMonorepo.$$super;

var textTop = Css_Js_Core$IsenseiMonorepo.textTop;

var textBottom = Css_Js_Core$IsenseiMonorepo.textBottom;

var middle = Css_Js_Core$IsenseiMonorepo.middle;

var normal = Css_Js_Core$IsenseiMonorepo.normal;

var breakAll = Css_Js_Core$IsenseiMonorepo.breakAll;

var keepAll = Css_Js_Core$IsenseiMonorepo.keepAll;

var breakWord = Css_Js_Core$IsenseiMonorepo.breakWord;

var reverse = Css_Js_Core$IsenseiMonorepo.reverse;

var alternate = Css_Js_Core$IsenseiMonorepo.alternate;

var alternateReverse = Css_Js_Core$IsenseiMonorepo.alternateReverse;

var fill = Css_Js_Core$IsenseiMonorepo.fill;

var content = Css_Js_Core$IsenseiMonorepo.content;

var maxContent = Css_Js_Core$IsenseiMonorepo.maxContent;

var minContent = Css_Js_Core$IsenseiMonorepo.minContent;

var fitContent = Css_Js_Core$IsenseiMonorepo.fitContent;

var all = Css_Js_Core$IsenseiMonorepo.all;

var round = Css_Js_Core$IsenseiMonorepo.round;

var miter = Css_Js_Core$IsenseiMonorepo.miter;

var bevel = Css_Js_Core$IsenseiMonorepo.bevel;

var butt = Css_Js_Core$IsenseiMonorepo.butt;

var square = Css_Js_Core$IsenseiMonorepo.square;

var thin = Css_Js_Core$IsenseiMonorepo.thin;

var extraLight = Css_Js_Core$IsenseiMonorepo.extraLight;

var light = Css_Js_Core$IsenseiMonorepo.light;

var medium = Css_Js_Core$IsenseiMonorepo.medium;

var semiBold = Css_Js_Core$IsenseiMonorepo.semiBold;

var bold = Css_Js_Core$IsenseiMonorepo.bold;

var extraBold = Css_Js_Core$IsenseiMonorepo.extraBold;

var lighter = Css_Js_Core$IsenseiMonorepo.lighter;

var bolder = Css_Js_Core$IsenseiMonorepo.bolder;

var fr = Css_Js_Core$IsenseiMonorepo.fr;

var vw = Css_Js_Core$IsenseiMonorepo.vw;

var localUrl = Css_Js_Core$IsenseiMonorepo.localUrl;

var url = Css_Js_Core$IsenseiMonorepo.url;

var linear = Css_Js_Core$IsenseiMonorepo.linear;

var ease = Css_Js_Core$IsenseiMonorepo.ease;

var easeIn = Css_Js_Core$IsenseiMonorepo.easeIn;

var easeOut = Css_Js_Core$IsenseiMonorepo.easeOut;

var easeInOut = Css_Js_Core$IsenseiMonorepo.easeInOut;

var stepStart = Css_Js_Core$IsenseiMonorepo.stepStart;

var stepEnd = Css_Js_Core$IsenseiMonorepo.stepEnd;

var steps = Css_Js_Core$IsenseiMonorepo.steps;

var cubicBezier = Css_Js_Core$IsenseiMonorepo.cubicBezier;

var marginBox = Css_Js_Core$IsenseiMonorepo.marginBox;

var fillBox = Css_Js_Core$IsenseiMonorepo.fillBox;

var strokeBox = Css_Js_Core$IsenseiMonorepo.strokeBox;

var viewBox = Css_Js_Core$IsenseiMonorepo.viewBox;

var translate = Css_Js_Core$IsenseiMonorepo.translate;

var translate3d = Css_Js_Core$IsenseiMonorepo.translate3d;

var translateX = Css_Js_Core$IsenseiMonorepo.translateX;

var translateY = Css_Js_Core$IsenseiMonorepo.translateY;

var translateZ = Css_Js_Core$IsenseiMonorepo.translateZ;

var scale = Css_Js_Core$IsenseiMonorepo.scale;

var scale3d = Css_Js_Core$IsenseiMonorepo.scale3d;

var scaleX = Css_Js_Core$IsenseiMonorepo.scaleX;

var scaleY = Css_Js_Core$IsenseiMonorepo.scaleY;

var scaleZ = Css_Js_Core$IsenseiMonorepo.scaleZ;

var rotate = Css_Js_Core$IsenseiMonorepo.rotate;

var rotate3d = Css_Js_Core$IsenseiMonorepo.rotate3d;

var rotateX = Css_Js_Core$IsenseiMonorepo.rotateX;

var rotateY = Css_Js_Core$IsenseiMonorepo.rotateY;

var rotateZ = Css_Js_Core$IsenseiMonorepo.rotateZ;

var skew = Css_Js_Core$IsenseiMonorepo.skew;

var skewX = Css_Js_Core$IsenseiMonorepo.skewX;

var skewY = Css_Js_Core$IsenseiMonorepo.skewY;

var linearGradient = Css_Js_Core$IsenseiMonorepo.linearGradient;

var repeatingLinearGradient = Css_Js_Core$IsenseiMonorepo.repeatingLinearGradient;

var radialGradient = Css_Js_Core$IsenseiMonorepo.radialGradient;

var repeatingRadialGradient = Css_Js_Core$IsenseiMonorepo.repeatingRadialGradient;

var areas = Css_Js_Core$IsenseiMonorepo.areas;

var ident = Css_Js_Core$IsenseiMonorepo.ident;

var numIdent = Css_Js_Core$IsenseiMonorepo.numIdent;

var contextMenu = Css_Js_Core$IsenseiMonorepo.contextMenu;

var help = Css_Js_Core$IsenseiMonorepo.help;

var pointer = Css_Js_Core$IsenseiMonorepo.pointer;

var progress = Css_Js_Core$IsenseiMonorepo.progress;

var wait = Css_Js_Core$IsenseiMonorepo.wait;

var cell = Css_Js_Core$IsenseiMonorepo.cell;

var crosshair = Css_Js_Core$IsenseiMonorepo.crosshair;

var verticalText = Css_Js_Core$IsenseiMonorepo.verticalText;

var alias = Css_Js_Core$IsenseiMonorepo.alias;

var copy = Css_Js_Core$IsenseiMonorepo.copy;

var move = Css_Js_Core$IsenseiMonorepo.move;

var noDrop = Css_Js_Core$IsenseiMonorepo.noDrop;

var notAllowed = Css_Js_Core$IsenseiMonorepo.notAllowed;

var grab = Css_Js_Core$IsenseiMonorepo.grab;

var grabbing = Css_Js_Core$IsenseiMonorepo.grabbing;

var allScroll = Css_Js_Core$IsenseiMonorepo.allScroll;

var colResize = Css_Js_Core$IsenseiMonorepo.colResize;

var rowResize = Css_Js_Core$IsenseiMonorepo.rowResize;

var nResize = Css_Js_Core$IsenseiMonorepo.nResize;

var eResize = Css_Js_Core$IsenseiMonorepo.eResize;

var sResize = Css_Js_Core$IsenseiMonorepo.sResize;

var wResize = Css_Js_Core$IsenseiMonorepo.wResize;

var neResize = Css_Js_Core$IsenseiMonorepo.neResize;

var nwResize = Css_Js_Core$IsenseiMonorepo.nwResize;

var seResize = Css_Js_Core$IsenseiMonorepo.seResize;

var swResize = Css_Js_Core$IsenseiMonorepo.swResize;

var ewResize = Css_Js_Core$IsenseiMonorepo.ewResize;

var nsResize = Css_Js_Core$IsenseiMonorepo.nsResize;

var neswResize = Css_Js_Core$IsenseiMonorepo.neswResize;

var nwseResize = Css_Js_Core$IsenseiMonorepo.nwseResize;

var zoomIn = Css_Js_Core$IsenseiMonorepo.zoomIn;

var zoomOut = Css_Js_Core$IsenseiMonorepo.zoomOut;

var flex3 = Css_Js_Core$IsenseiMonorepo.flex3;

var border = Css_Js_Core$IsenseiMonorepo.border;

var borderTop = Css_Js_Core$IsenseiMonorepo.borderTop;

var backgroundSize = Css_Js_Core$IsenseiMonorepo.backgroundSize;

var textDecoration = Css_Js_Core$IsenseiMonorepo.textDecoration;

var background = Css_Js_Core$IsenseiMonorepo.background;

var backgrounds = Css_Js_Core$IsenseiMonorepo.backgrounds;

var gridAutoColumns = Css_Js_Core$IsenseiMonorepo.gridAutoColumns;

var gridAutoRows = Css_Js_Core$IsenseiMonorepo.gridAutoRows;

var gridTemplateColumns = Css_Js_Core$IsenseiMonorepo.gridTemplateColumns;

var gridTemplateRows = Css_Js_Core$IsenseiMonorepo.gridTemplateRows;

var Calc = Css_Js_Core$IsenseiMonorepo.Calc;

var size = Css_Js_Core$IsenseiMonorepo.size;

var filter = Css_Js_Core$IsenseiMonorepo.filter;

var Transition = Css_Js_Core$IsenseiMonorepo.Transition;

var transitionValue = Css_Js_Core$IsenseiMonorepo.transitionValue;

var transitionList = Css_Js_Core$IsenseiMonorepo.transitionList;

var transition = Css_Js_Core$IsenseiMonorepo.transition;

var transitions = Css_Js_Core$IsenseiMonorepo.transitions;

var Animation = Css_Js_Core$IsenseiMonorepo.Animation;

var animationValue = Css_Js_Core$IsenseiMonorepo.animationValue;

var animation = Css_Js_Core$IsenseiMonorepo.animation;

var animations = Css_Js_Core$IsenseiMonorepo.animations;

var animationName = Css_Js_Core$IsenseiMonorepo.animationName;

var SVG = Css_Js_Core$IsenseiMonorepo.SVG;

var aliceblue = Css_Colors$IsenseiMonorepo.aliceblue;

var antiquewhite = Css_Colors$IsenseiMonorepo.antiquewhite;

var aqua = Css_Colors$IsenseiMonorepo.aqua;

var aquamarine = Css_Colors$IsenseiMonorepo.aquamarine;

var azure = Css_Colors$IsenseiMonorepo.azure;

var beige = Css_Colors$IsenseiMonorepo.beige;

var bisque = Css_Colors$IsenseiMonorepo.bisque;

var black = Css_Colors$IsenseiMonorepo.black;

var blanchedalmond = Css_Colors$IsenseiMonorepo.blanchedalmond;

var blue = Css_Colors$IsenseiMonorepo.blue;

var blueviolet = Css_Colors$IsenseiMonorepo.blueviolet;

var brown = Css_Colors$IsenseiMonorepo.brown;

var burlywood = Css_Colors$IsenseiMonorepo.burlywood;

var cadetblue = Css_Colors$IsenseiMonorepo.cadetblue;

var chartreuse = Css_Colors$IsenseiMonorepo.chartreuse;

var chocolate = Css_Colors$IsenseiMonorepo.chocolate;

var coral = Css_Colors$IsenseiMonorepo.coral;

var cornflowerblue = Css_Colors$IsenseiMonorepo.cornflowerblue;

var cornsilk = Css_Colors$IsenseiMonorepo.cornsilk;

var crimson = Css_Colors$IsenseiMonorepo.crimson;

var cyan = Css_Colors$IsenseiMonorepo.cyan;

var darkblue = Css_Colors$IsenseiMonorepo.darkblue;

var darkcyan = Css_Colors$IsenseiMonorepo.darkcyan;

var darkgoldenrod = Css_Colors$IsenseiMonorepo.darkgoldenrod;

var darkgray = Css_Colors$IsenseiMonorepo.darkgray;

var darkgreen = Css_Colors$IsenseiMonorepo.darkgreen;

var darkgrey = Css_Colors$IsenseiMonorepo.darkgrey;

var darkkhaki = Css_Colors$IsenseiMonorepo.darkkhaki;

var darkmagenta = Css_Colors$IsenseiMonorepo.darkmagenta;

var darkolivegreen = Css_Colors$IsenseiMonorepo.darkolivegreen;

var darkorange = Css_Colors$IsenseiMonorepo.darkorange;

var darkorchid = Css_Colors$IsenseiMonorepo.darkorchid;

var darkred = Css_Colors$IsenseiMonorepo.darkred;

var darksalmon = Css_Colors$IsenseiMonorepo.darksalmon;

var darkseagreen = Css_Colors$IsenseiMonorepo.darkseagreen;

var darkslateblue = Css_Colors$IsenseiMonorepo.darkslateblue;

var darkslategray = Css_Colors$IsenseiMonorepo.darkslategray;

var darkslategrey = Css_Colors$IsenseiMonorepo.darkslategrey;

var darkturquoise = Css_Colors$IsenseiMonorepo.darkturquoise;

var darkviolet = Css_Colors$IsenseiMonorepo.darkviolet;

var deeppink = Css_Colors$IsenseiMonorepo.deeppink;

var deepskyblue = Css_Colors$IsenseiMonorepo.deepskyblue;

var dimgray = Css_Colors$IsenseiMonorepo.dimgray;

var dimgrey = Css_Colors$IsenseiMonorepo.dimgrey;

var dodgerblue = Css_Colors$IsenseiMonorepo.dodgerblue;

var firebrick = Css_Colors$IsenseiMonorepo.firebrick;

var floralwhite = Css_Colors$IsenseiMonorepo.floralwhite;

var forestgreen = Css_Colors$IsenseiMonorepo.forestgreen;

var fuchsia = Css_Colors$IsenseiMonorepo.fuchsia;

var gainsboro = Css_Colors$IsenseiMonorepo.gainsboro;

var ghostwhite = Css_Colors$IsenseiMonorepo.ghostwhite;

var gold = Css_Colors$IsenseiMonorepo.gold;

var goldenrod = Css_Colors$IsenseiMonorepo.goldenrod;

var gray = Css_Colors$IsenseiMonorepo.gray;

var green = Css_Colors$IsenseiMonorepo.green;

var greenyellow = Css_Colors$IsenseiMonorepo.greenyellow;

var grey = Css_Colors$IsenseiMonorepo.grey;

var honeydew = Css_Colors$IsenseiMonorepo.honeydew;

var hotpink = Css_Colors$IsenseiMonorepo.hotpink;

var indianred = Css_Colors$IsenseiMonorepo.indianred;

var indigo = Css_Colors$IsenseiMonorepo.indigo;

var ivory = Css_Colors$IsenseiMonorepo.ivory;

var khaki = Css_Colors$IsenseiMonorepo.khaki;

var lavender = Css_Colors$IsenseiMonorepo.lavender;

var lavenderblush = Css_Colors$IsenseiMonorepo.lavenderblush;

var lawngreen = Css_Colors$IsenseiMonorepo.lawngreen;

var lemonchiffon = Css_Colors$IsenseiMonorepo.lemonchiffon;

var lightblue = Css_Colors$IsenseiMonorepo.lightblue;

var lightcoral = Css_Colors$IsenseiMonorepo.lightcoral;

var lightcyan = Css_Colors$IsenseiMonorepo.lightcyan;

var lightgoldenrodyellow = Css_Colors$IsenseiMonorepo.lightgoldenrodyellow;

var lightgray = Css_Colors$IsenseiMonorepo.lightgray;

var lightgreen = Css_Colors$IsenseiMonorepo.lightgreen;

var lightgrey = Css_Colors$IsenseiMonorepo.lightgrey;

var lightpink = Css_Colors$IsenseiMonorepo.lightpink;

var lightsalmon = Css_Colors$IsenseiMonorepo.lightsalmon;

var lightseagreen = Css_Colors$IsenseiMonorepo.lightseagreen;

var lightskyblue = Css_Colors$IsenseiMonorepo.lightskyblue;

var lightslategray = Css_Colors$IsenseiMonorepo.lightslategray;

var lightslategrey = Css_Colors$IsenseiMonorepo.lightslategrey;

var lightsteelblue = Css_Colors$IsenseiMonorepo.lightsteelblue;

var lightyellow = Css_Colors$IsenseiMonorepo.lightyellow;

var lime = Css_Colors$IsenseiMonorepo.lime;

var limegreen = Css_Colors$IsenseiMonorepo.limegreen;

var linen = Css_Colors$IsenseiMonorepo.linen;

var magenta = Css_Colors$IsenseiMonorepo.magenta;

var maroon = Css_Colors$IsenseiMonorepo.maroon;

var mediumaquamarine = Css_Colors$IsenseiMonorepo.mediumaquamarine;

var mediumblue = Css_Colors$IsenseiMonorepo.mediumblue;

var mediumorchid = Css_Colors$IsenseiMonorepo.mediumorchid;

var mediumpurple = Css_Colors$IsenseiMonorepo.mediumpurple;

var mediumseagreen = Css_Colors$IsenseiMonorepo.mediumseagreen;

var mediumslateblue = Css_Colors$IsenseiMonorepo.mediumslateblue;

var mediumspringgreen = Css_Colors$IsenseiMonorepo.mediumspringgreen;

var mediumturquoise = Css_Colors$IsenseiMonorepo.mediumturquoise;

var mediumvioletred = Css_Colors$IsenseiMonorepo.mediumvioletred;

var midnightblue = Css_Colors$IsenseiMonorepo.midnightblue;

var mintcream = Css_Colors$IsenseiMonorepo.mintcream;

var mistyrose = Css_Colors$IsenseiMonorepo.mistyrose;

var moccasin = Css_Colors$IsenseiMonorepo.moccasin;

var navajowhite = Css_Colors$IsenseiMonorepo.navajowhite;

var navy = Css_Colors$IsenseiMonorepo.navy;

var oldlace = Css_Colors$IsenseiMonorepo.oldlace;

var olive = Css_Colors$IsenseiMonorepo.olive;

var olivedrab = Css_Colors$IsenseiMonorepo.olivedrab;

var orange = Css_Colors$IsenseiMonorepo.orange;

var orangered = Css_Colors$IsenseiMonorepo.orangered;

var orchid = Css_Colors$IsenseiMonorepo.orchid;

var palegoldenrod = Css_Colors$IsenseiMonorepo.palegoldenrod;

var palegreen = Css_Colors$IsenseiMonorepo.palegreen;

var paleturquoise = Css_Colors$IsenseiMonorepo.paleturquoise;

var palevioletred = Css_Colors$IsenseiMonorepo.palevioletred;

var papayawhip = Css_Colors$IsenseiMonorepo.papayawhip;

var peachpuff = Css_Colors$IsenseiMonorepo.peachpuff;

var peru = Css_Colors$IsenseiMonorepo.peru;

var pink = Css_Colors$IsenseiMonorepo.pink;

var plum = Css_Colors$IsenseiMonorepo.plum;

var powderblue = Css_Colors$IsenseiMonorepo.powderblue;

var purple = Css_Colors$IsenseiMonorepo.purple;

var rebeccapurple = Css_Colors$IsenseiMonorepo.rebeccapurple;

var red = Css_Colors$IsenseiMonorepo.red;

var rosybrown = Css_Colors$IsenseiMonorepo.rosybrown;

var royalblue = Css_Colors$IsenseiMonorepo.royalblue;

var saddlebrown = Css_Colors$IsenseiMonorepo.saddlebrown;

var salmon = Css_Colors$IsenseiMonorepo.salmon;

var sandybrown = Css_Colors$IsenseiMonorepo.sandybrown;

var seagreen = Css_Colors$IsenseiMonorepo.seagreen;

var seashell = Css_Colors$IsenseiMonorepo.seashell;

var sienna = Css_Colors$IsenseiMonorepo.sienna;

var silver = Css_Colors$IsenseiMonorepo.silver;

var skyblue = Css_Colors$IsenseiMonorepo.skyblue;

var slateblue = Css_Colors$IsenseiMonorepo.slateblue;

var slategray = Css_Colors$IsenseiMonorepo.slategray;

var slategrey = Css_Colors$IsenseiMonorepo.slategrey;

var snow = Css_Colors$IsenseiMonorepo.snow;

var springgreen = Css_Colors$IsenseiMonorepo.springgreen;

var steelblue = Css_Colors$IsenseiMonorepo.steelblue;

var tan = Css_Colors$IsenseiMonorepo.tan;

var teal = Css_Colors$IsenseiMonorepo.teal;

var thistle = Css_Colors$IsenseiMonorepo.thistle;

var tomato = Css_Colors$IsenseiMonorepo.tomato;

var turquoise = Css_Colors$IsenseiMonorepo.turquoise;

var violet = Css_Colors$IsenseiMonorepo.violet;

var wheat = Css_Colors$IsenseiMonorepo.wheat;

var white = Css_Colors$IsenseiMonorepo.white;

var whitesmoke = Css_Colors$IsenseiMonorepo.whitesmoke;

var yellow = Css_Colors$IsenseiMonorepo.yellow;

var yellowgreen = Css_Colors$IsenseiMonorepo.yellowgreen;

var transparent = Css_Colors$IsenseiMonorepo.transparent;

var renderRule = include.renderRule;

var $$global = include.$$global;

var renderGlobal = include.renderGlobal;

var style = include.style;

var merge = include.merge;

var merge2 = include.merge2;

var merge3 = include.merge3;

var merge4 = include.merge4;

var keyframes = include.keyframes;

var renderKeyframes$1 = include.renderKeyframes;

export {
  Types ,
  Make ,
  toJson ,
  important ,
  label ,
  Shadow ,
  unsafe ,
  alignContent ,
  alignItems ,
  alignSelf ,
  animationDelay ,
  animationDirection ,
  animationDuration ,
  animationFillMode ,
  animationIterationCount ,
  animationPlayState ,
  animationTimingFunction ,
  backdropFilter ,
  backfaceVisibility ,
  backgroundAttachment ,
  backgroundColor ,
  backgroundClip ,
  backgroundImage ,
  backgroundOrigin ,
  backgroundPosition ,
  backgroundPositions ,
  backgroundPosition4 ,
  backgroundRepeat ,
  borderBottom ,
  borderBottomColor ,
  borderBottomLeftRadius ,
  borderBottomRightRadius ,
  borderBottomStyle ,
  borderBottomWidth ,
  borderCollapse ,
  borderColor ,
  borderLeft ,
  borderLeftColor ,
  borderLeftStyle ,
  borderLeftWidth ,
  borderRight ,
  borderRightColor ,
  borderRightStyle ,
  borderRightWidth ,
  borderRadius ,
  borderRadius4 ,
  borderSpacing ,
  borderStyle ,
  borderTopColor ,
  borderTopLeftRadius ,
  borderTopRightRadius ,
  borderTopStyle ,
  borderTopWidth ,
  borderWidth ,
  bottom ,
  boxSizing ,
  boxShadow ,
  boxShadows ,
  clear ,
  clipPath ,
  color ,
  columnCount ,
  contentRule ,
  contentRules ,
  counterIncrement ,
  countersIncrement ,
  counterReset ,
  countersReset ,
  counterSet ,
  countersSet ,
  cursor ,
  direction ,
  display ,
  flex ,
  flexBasis ,
  flexDirection ,
  flexGrow ,
  flexShrink ,
  flexWrap ,
  $$float ,
  fontFamily ,
  fontFamilies ,
  fontSize ,
  fontStyle ,
  fontVariant ,
  fontWeight ,
  gridArea ,
  gridArea2 ,
  gridArea3 ,
  gridArea4 ,
  gridAutoFlow ,
  gridColumn ,
  gridColumnEnd ,
  columnGap ,
  scrollBehavior ,
  columnWidth ,
  caretColor ,
  gridColumnGap ,
  gridColumnStart ,
  gap ,
  gap2 ,
  gridGap ,
  gridRow ,
  gridRowEnd ,
  gridRowGap ,
  rowGap ,
  gridRowStart ,
  gridTemplateAreas ,
  height ,
  justifyContent ,
  justifyItems ,
  justifySelf ,
  left ,
  letterSpacing ,
  lineHeight ,
  listStyle ,
  listStyleImage ,
  listStyleType ,
  listStylePosition ,
  margin ,
  margin2 ,
  margin3 ,
  margin4 ,
  marginLeft ,
  marginRight ,
  marginTop ,
  marginBottom ,
  maxHeight ,
  maxWidth ,
  minHeight ,
  minWidth ,
  objectFit ,
  objectPosition ,
  opacity ,
  order ,
  outline ,
  outlineColor ,
  outlineOffset ,
  outlineStyle ,
  outlineWidth ,
  overflow ,
  overflowX ,
  overflowY ,
  overflowWrap ,
  padding ,
  padding2 ,
  padding3 ,
  padding4 ,
  paddingLeft ,
  paddingRight ,
  paddingTop ,
  paddingBottom ,
  perspective ,
  perspectiveOrigin ,
  pointerEvents ,
  position ,
  resize ,
  right ,
  tableLayout ,
  textAlign ,
  textDecorationColor ,
  textDecorationLine ,
  textDecorationStyle ,
  textIndent ,
  textOverflow ,
  textShadow ,
  textShadows ,
  textTransform ,
  top ,
  transform ,
  transforms ,
  transformOrigin ,
  transformOrigin3d ,
  transitionDelay ,
  transitionDuration ,
  transitionProperty ,
  transformStyle ,
  transitionTimingFunction ,
  userSelect ,
  verticalAlign ,
  visibility ,
  width ,
  whiteSpace ,
  wordBreak ,
  wordSpacing ,
  wordWrap ,
  zIndex ,
  selector ,
  media ,
  active ,
  checked ,
  $$default ,
  $$default as default,
  defined ,
  disabled ,
  empty ,
  enabled ,
  first ,
  firstChild ,
  firstOfType ,
  focus ,
  focusVisible ,
  focusWithin ,
  host ,
  hover ,
  indeterminate ,
  inRange ,
  invalid ,
  lang ,
  lastChild ,
  lastOfType ,
  link ,
  not__ ,
  Nth ,
  nthChild ,
  nthLastChild ,
  nthLastOfType ,
  nthOfType ,
  onlyChild ,
  onlyOfType ,
  optional ,
  outOfRange ,
  readOnly ,
  readWrite ,
  required ,
  root ,
  scope ,
  target ,
  valid ,
  visited ,
  after ,
  before ,
  firstLetter ,
  firstLine ,
  placeholder ,
  selection ,
  child ,
  children ,
  directSibling ,
  siblings ,
  anyLink ,
  initial ,
  inherit_ ,
  unset ,
  $$var ,
  varDefault ,
  auto ,
  none ,
  text ,
  pct ,
  ch ,
  cm ,
  em ,
  ex ,
  mm ,
  pt ,
  px ,
  pxFloat ,
  rem ,
  vh ,
  vmin ,
  vmax ,
  zero ,
  deg ,
  rad ,
  grad ,
  turn ,
  ltr ,
  rtl ,
  absolute ,
  relative ,
  $$static ,
  fixed ,
  sticky ,
  horizontal ,
  vertical ,
  smallCaps ,
  italic ,
  oblique ,
  hidden ,
  visible ,
  scroll ,
  rgb ,
  rgba ,
  hsl ,
  hsla ,
  hex ,
  currentColor ,
  local ,
  paddingBox ,
  borderBox ,
  contentBox ,
  noRepeat ,
  space ,
  repeat ,
  minmax ,
  repeatX ,
  repeatY ,
  contain ,
  cover ,
  row ,
  rowReverse ,
  column ,
  columnReverse ,
  wrap ,
  nowrap ,
  wrapReverse ,
  inline ,
  block ,
  contents ,
  flexBox ,
  grid ,
  inlineBlock ,
  inlineFlex ,
  inlineGrid ,
  inlineTable ,
  listItem ,
  runIn ,
  table ,
  tableCaption ,
  tableColumnGroup ,
  tableHeaderGroup ,
  tableFooterGroup ,
  tableRowGroup ,
  tableCell ,
  tableColumn ,
  tableRow ,
  flexStart ,
  flexEnd ,
  center ,
  stretch ,
  spaceBetween ,
  spaceAround ,
  spaceEvenly ,
  baseline ,
  forwards ,
  backwards ,
  both ,
  infinite ,
  count ,
  paused ,
  running ,
  inside ,
  outside ,
  solid ,
  dotted ,
  dashed ,
  underline ,
  overline ,
  lineThrough ,
  clip ,
  ellipsis ,
  wavy ,
  $$double ,
  uppercase ,
  lowercase ,
  capitalize ,
  sub ,
  $$super ,
  textTop ,
  textBottom ,
  middle ,
  normal ,
  breakAll ,
  keepAll ,
  breakWord ,
  reverse ,
  alternate ,
  alternateReverse ,
  fill ,
  content ,
  maxContent ,
  minContent ,
  fitContent ,
  all ,
  round ,
  miter ,
  bevel ,
  butt ,
  square ,
  thin ,
  extraLight ,
  light ,
  medium ,
  semiBold ,
  bold ,
  extraBold ,
  lighter ,
  bolder ,
  fr ,
  vw ,
  localUrl ,
  url ,
  linear ,
  ease ,
  easeIn ,
  easeOut ,
  easeInOut ,
  stepStart ,
  stepEnd ,
  steps ,
  cubicBezier ,
  marginBox ,
  fillBox ,
  strokeBox ,
  viewBox ,
  translate ,
  translate3d ,
  translateX ,
  translateY ,
  translateZ ,
  scale ,
  scale3d ,
  scaleX ,
  scaleY ,
  scaleZ ,
  rotate ,
  rotate3d ,
  rotateX ,
  rotateY ,
  rotateZ ,
  skew ,
  skewX ,
  skewY ,
  linearGradient ,
  repeatingLinearGradient ,
  radialGradient ,
  repeatingRadialGradient ,
  areas ,
  ident ,
  numIdent ,
  contextMenu ,
  help ,
  pointer ,
  progress ,
  wait ,
  cell ,
  crosshair ,
  verticalText ,
  alias ,
  copy ,
  move ,
  noDrop ,
  notAllowed ,
  grab ,
  grabbing ,
  allScroll ,
  colResize ,
  rowResize ,
  nResize ,
  eResize ,
  sResize ,
  wResize ,
  neResize ,
  nwResize ,
  seResize ,
  swResize ,
  ewResize ,
  nsResize ,
  neswResize ,
  nwseResize ,
  zoomIn ,
  zoomOut ,
  flex3 ,
  border ,
  borderTop ,
  backgroundSize ,
  textDecoration ,
  background ,
  backgrounds ,
  gridAutoColumns ,
  gridAutoRows ,
  gridTemplateColumns ,
  gridTemplateRows ,
  Calc ,
  size ,
  filter ,
  Transition ,
  transitionValue ,
  transitionList ,
  transition ,
  transitions ,
  Animation ,
  animationValue ,
  animation ,
  animations ,
  animationName ,
  SVG ,
  aliceblue ,
  antiquewhite ,
  aqua ,
  aquamarine ,
  azure ,
  beige ,
  bisque ,
  black ,
  blanchedalmond ,
  blue ,
  blueviolet ,
  brown ,
  burlywood ,
  cadetblue ,
  chartreuse ,
  chocolate ,
  coral ,
  cornflowerblue ,
  cornsilk ,
  crimson ,
  cyan ,
  darkblue ,
  darkcyan ,
  darkgoldenrod ,
  darkgray ,
  darkgreen ,
  darkgrey ,
  darkkhaki ,
  darkmagenta ,
  darkolivegreen ,
  darkorange ,
  darkorchid ,
  darkred ,
  darksalmon ,
  darkseagreen ,
  darkslateblue ,
  darkslategray ,
  darkslategrey ,
  darkturquoise ,
  darkviolet ,
  deeppink ,
  deepskyblue ,
  dimgray ,
  dimgrey ,
  dodgerblue ,
  firebrick ,
  floralwhite ,
  forestgreen ,
  fuchsia ,
  gainsboro ,
  ghostwhite ,
  gold ,
  goldenrod ,
  gray ,
  green ,
  greenyellow ,
  grey ,
  honeydew ,
  hotpink ,
  indianred ,
  indigo ,
  ivory ,
  khaki ,
  lavender ,
  lavenderblush ,
  lawngreen ,
  lemonchiffon ,
  lightblue ,
  lightcoral ,
  lightcyan ,
  lightgoldenrodyellow ,
  lightgray ,
  lightgreen ,
  lightgrey ,
  lightpink ,
  lightsalmon ,
  lightseagreen ,
  lightskyblue ,
  lightslategray ,
  lightslategrey ,
  lightsteelblue ,
  lightyellow ,
  lime ,
  limegreen ,
  linen ,
  magenta ,
  maroon ,
  mediumaquamarine ,
  mediumblue ,
  mediumorchid ,
  mediumpurple ,
  mediumseagreen ,
  mediumslateblue ,
  mediumspringgreen ,
  mediumturquoise ,
  mediumvioletred ,
  midnightblue ,
  mintcream ,
  mistyrose ,
  moccasin ,
  navajowhite ,
  navy ,
  oldlace ,
  olive ,
  olivedrab ,
  orange ,
  orangered ,
  orchid ,
  palegoldenrod ,
  palegreen ,
  paleturquoise ,
  palevioletred ,
  papayawhip ,
  peachpuff ,
  peru ,
  pink ,
  plum ,
  powderblue ,
  purple ,
  rebeccapurple ,
  red ,
  rosybrown ,
  royalblue ,
  saddlebrown ,
  salmon ,
  sandybrown ,
  seagreen ,
  seashell ,
  sienna ,
  silver ,
  skyblue ,
  slateblue ,
  slategray ,
  slategrey ,
  snow ,
  springgreen ,
  steelblue ,
  tan ,
  teal ,
  thistle ,
  tomato ,
  turquoise ,
  violet ,
  wheat ,
  white ,
  whitesmoke ,
  yellow ,
  yellowgreen ,
  transparent ,
  insertRule ,
  renderRule ,
  $$global ,
  renderGlobal ,
  style ,
  merge ,
  merge2 ,
  merge3 ,
  merge4 ,
  keyframes ,
  renderKeyframes$1 as renderKeyframes,
  fontFace ,
  
}
/* include Not a pure module */
