// Generated by ReScript, PLEASE EDIT WITH CARE


var Button = {};

var Label = {};

var Options = {};

var $$Option = {};

export {
  Button ,
  Label ,
  Options ,
  $$Option ,
  
}
/* No side effect */
