// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Button__UI(Props) {
  return React.createElement("div", undefined, "Component Button");
}

var make = Button__UI;

export {
  make ,
  
}
/* react Not a pure module */
