// Generated by ReScript, PLEASE EDIT WITH CARE


var AcademicCapIcon = {};

var AdjustmentsIcon = {};

var AnnotationIcon = {};

var ArchiveIcon = {};

var ArrowCircleDownIcon = {};

var ArrowCircleLeftIcon = {};

var ArrowCircleRightIcon = {};

var ArrowCircleUpIcon = {};

var ArrowDownIcon = {};

var ArrowLeftIcon = {};

var ArrowNarrowDownIcon = {};

var ArrowNarrowLeftIcon = {};

var ArrowNarrowRightIcon = {};

var ArrowNarrowUpIcon = {};

var ArrowRightIcon = {};

var ArrowSmDownIcon = {};

var ArrowSmLeftIcon = {};

var ArrowSmRightIcon = {};

var ArrowSmUpIcon = {};

var ArrowUpIcon = {};

var ArrowsExpandIcon = {};

var AtSymbolIcon = {};

var BackspaceIcon = {};

var BadgeCheckIcon = {};

var BanIcon = {};

var BeakerIcon = {};

var BellIcon = {};

var BookOpenIcon = {};

var BookmarkAltIcon = {};

var BookmarkIcon = {};

var BriefcaseIcon = {};

var CakeIcon = {};

var CalculatorIcon = {};

var CalendarIcon = {};

var CameraIcon = {};

var CashIcon = {};

var ChartBarIcon = {};

var ChartPieIcon = {};

var ChartSquareBarIcon = {};

var ChatAlt2Icon = {};

var ChatAltIcon = {};

var ChatIcon = {};

var CheckCircleIcon = {};

var CheckIcon = {};

var ChevronDoubleDownIcon = {};

var ChevronDoubleLeftIcon = {};

var ChevronDoubleRightIcon = {};

var ChevronDoubleUpIcon = {};

var ChevronDownIcon = {};

var ChevronLeftIcon = {};

var ChevronRightIcon = {};

var ChevronUpIcon = {};

var ChipIcon = {};

var ClipboardCheckIcon = {};

var ClipboardCopyIcon = {};

var ClipboardIcon = {};

var ClipboardListIcon = {};

var ClockIcon = {};

var CloudDownloadIcon = {};

var CloudIcon = {};

var CloudUploadIcon = {};

var CodeIcon = {};

var CogIcon = {};

var CollectionIcon = {};

var ColorSwatchIcon = {};

var CreditCardIcon = {};

var CubeIcon = {};

var CubeTransparentIcon = {};

var CurrencyBangladeshiIcon = {};

var CurrencyDollarIcon = {};

var CurrencyEuroIcon = {};

var CurrencyPoundIcon = {};

var CurrencyRupeeIcon = {};

var CurrencyYenIcon = {};

var CursorClickIcon = {};

var DatabaseIcon = {};

var DesktopComputerIcon = {};

var DeviceMobileIcon = {};

var DeviceTabletIcon = {};

var DocumentAddIcon = {};

var DocumentDownloadIcon = {};

var DocumentDuplicateIcon = {};

var DocumentIcon = {};

var DocumentRemoveIcon = {};

var DocumentReportIcon = {};

var DocumentSearchIcon = {};

var DocumentTextIcon = {};

var DotsCircleHorizontalIcon = {};

var DotsHorizontalIcon = {};

var DotsVerticalIcon = {};

var DownloadIcon = {};

var DuplicateIcon = {};

var EmojiHappyIcon = {};

var EmojiSadIcon = {};

var ExclamationCircleIcon = {};

var ExclamationIcon = {};

var ExternalLinkIcon = {};

var EyeIcon = {};

var EyeOffIcon = {};

var FastForwardIcon = {};

var FilmIcon = {};

var FilterIcon = {};

var FingerPrintIcon = {};

var FireIcon = {};

var FlagIcon = {};

var FolderAddIcon = {};

var FolderDownloadIcon = {};

var FolderIcon = {};

var FolderOpenIcon = {};

var FolderRemoveIcon = {};

var GiftIcon = {};

var GlobeAltIcon = {};

var GlobeIcon = {};

var HandIcon = {};

var HashtagIcon = {};

var HeartIcon = {};

var HomeIcon = {};

var IdentificationIcon = {};

var InboxIcon = {};

var InboxInIcon = {};

var InformationCircleIcon = {};

var KeyIcon = {};

var LibraryIcon = {};

var LightBulbIcon = {};

var LightningBoltIcon = {};

var LinkIcon = {};

var LocationMarkerIcon = {};

var LockClosedIcon = {};

var LockOpenIcon = {};

var LoginIcon = {};

var LogoutIcon = {};

var MailIcon = {};

var MailOpenIcon = {};

var MapIcon = {};

var MenuAlt1Icon = {};

var MenuAlt2Icon = {};

var MenuAlt3Icon = {};

var MenuAlt4Icon = {};

var MenuIcon = {};

var MicrophoneIcon = {};

var MinusCircleIcon = {};

var MinusIcon = {};

var MinusSmIcon = {};

var MoonIcon = {};

var MusicNoteIcon = {};

var NewspaperIcon = {};

var OfficeBuildingIcon = {};

var PaperAirplaneIcon = {};

var PaperClipIcon = {};

var PauseIcon = {};

var PencilAltIcon = {};

var PencilIcon = {};

var PhoneIcon = {};

var PhoneIncomingIcon = {};

var PhoneMissedCallIcon = {};

var PhoneOutgoingIcon = {};

var PhotographIcon = {};

var PlayIcon = {};

var PlusCircleIcon = {};

var PlusIcon = {};

var PlusSmIcon = {};

var PresentationChartBarIcon = {};

var PresentationChartLineIcon = {};

var PrinterIcon = {};

var PuzzleIcon = {};

var QrcodeIcon = {};

var QuestionMarkCircleIcon = {};

var ReceiptRefundIcon = {};

var ReceiptTaxIcon = {};

var RefreshIcon = {};

var ReplyIcon = {};

var RewindIcon = {};

var RssIcon = {};

var SaveAsIcon = {};

var SaveIcon = {};

var ScaleIcon = {};

var ScissorsIcon = {};

var SearchCircleIcon = {};

var SearchIcon = {};

var SelectorIcon = {};

var ServerIcon = {};

var ShareIcon = {};

var ShieldCheckIcon = {};

var ShieldExclamationIcon = {};

var ShoppingBagIcon = {};

var ShoppingCartIcon = {};

var SortAscendingIcon = {};

var SortDescendingIcon = {};

var SparklesIcon = {};

var SpeakerphoneIcon = {};

var StarIcon = {};

var StatusOfflineIcon = {};

var StatusOnlineIcon = {};

var StopIcon = {};

var SunIcon = {};

var SupportIcon = {};

var SwitchHorizontalIcon = {};

var SwitchVerticalIcon = {};

var TableIcon = {};

var TagIcon = {};

var TemplateIcon = {};

var TerminalIcon = {};

var ThumbDownIcon = {};

var ThumbUpIcon = {};

var TicketIcon = {};

var TranslateIcon = {};

var TrashIcon = {};

var TrendingDownIcon = {};

var TrendingUpIcon = {};

var TruckIcon = {};

var UploadIcon = {};

var UserAddIcon = {};

var UserCircleIcon = {};

var UserGroupIcon = {};

var UserIcon = {};

var UserRemoveIcon = {};

var UsersIcon = {};

var VariableIcon = {};

var VideoCameraIcon = {};

var ViewBoardsIcon = {};

var ViewGridAddIcon = {};

var ViewGridIcon = {};

var ViewListIcon = {};

var VolumeOffIcon = {};

var VolumeUpIcon = {};

var WifiIcon = {};

var XCircleIcon = {};

var XIcon = {};

var ZoomInIcon = {};

var ZoomOutIcon = {};

var Solid = {
  AcademicCapIcon: AcademicCapIcon,
  AdjustmentsIcon: AdjustmentsIcon,
  AnnotationIcon: AnnotationIcon,
  ArchiveIcon: ArchiveIcon,
  ArrowCircleDownIcon: ArrowCircleDownIcon,
  ArrowCircleLeftIcon: ArrowCircleLeftIcon,
  ArrowCircleRightIcon: ArrowCircleRightIcon,
  ArrowCircleUpIcon: ArrowCircleUpIcon,
  ArrowDownIcon: ArrowDownIcon,
  ArrowLeftIcon: ArrowLeftIcon,
  ArrowNarrowDownIcon: ArrowNarrowDownIcon,
  ArrowNarrowLeftIcon: ArrowNarrowLeftIcon,
  ArrowNarrowRightIcon: ArrowNarrowRightIcon,
  ArrowNarrowUpIcon: ArrowNarrowUpIcon,
  ArrowRightIcon: ArrowRightIcon,
  ArrowSmDownIcon: ArrowSmDownIcon,
  ArrowSmLeftIcon: ArrowSmLeftIcon,
  ArrowSmRightIcon: ArrowSmRightIcon,
  ArrowSmUpIcon: ArrowSmUpIcon,
  ArrowUpIcon: ArrowUpIcon,
  ArrowsExpandIcon: ArrowsExpandIcon,
  AtSymbolIcon: AtSymbolIcon,
  BackspaceIcon: BackspaceIcon,
  BadgeCheckIcon: BadgeCheckIcon,
  BanIcon: BanIcon,
  BeakerIcon: BeakerIcon,
  BellIcon: BellIcon,
  BookOpenIcon: BookOpenIcon,
  BookmarkAltIcon: BookmarkAltIcon,
  BookmarkIcon: BookmarkIcon,
  BriefcaseIcon: BriefcaseIcon,
  CakeIcon: CakeIcon,
  CalculatorIcon: CalculatorIcon,
  CalendarIcon: CalendarIcon,
  CameraIcon: CameraIcon,
  CashIcon: CashIcon,
  ChartBarIcon: ChartBarIcon,
  ChartPieIcon: ChartPieIcon,
  ChartSquareBarIcon: ChartSquareBarIcon,
  ChatAlt2Icon: ChatAlt2Icon,
  ChatAltIcon: ChatAltIcon,
  ChatIcon: ChatIcon,
  CheckCircleIcon: CheckCircleIcon,
  CheckIcon: CheckIcon,
  ChevronDoubleDownIcon: ChevronDoubleDownIcon,
  ChevronDoubleLeftIcon: ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon: ChevronDoubleRightIcon,
  ChevronDoubleUpIcon: ChevronDoubleUpIcon,
  ChevronDownIcon: ChevronDownIcon,
  ChevronLeftIcon: ChevronLeftIcon,
  ChevronRightIcon: ChevronRightIcon,
  ChevronUpIcon: ChevronUpIcon,
  ChipIcon: ChipIcon,
  ClipboardCheckIcon: ClipboardCheckIcon,
  ClipboardCopyIcon: ClipboardCopyIcon,
  ClipboardIcon: ClipboardIcon,
  ClipboardListIcon: ClipboardListIcon,
  ClockIcon: ClockIcon,
  CloudDownloadIcon: CloudDownloadIcon,
  CloudIcon: CloudIcon,
  CloudUploadIcon: CloudUploadIcon,
  CodeIcon: CodeIcon,
  CogIcon: CogIcon,
  CollectionIcon: CollectionIcon,
  ColorSwatchIcon: ColorSwatchIcon,
  CreditCardIcon: CreditCardIcon,
  CubeIcon: CubeIcon,
  CubeTransparentIcon: CubeTransparentIcon,
  CurrencyBangladeshiIcon: CurrencyBangladeshiIcon,
  CurrencyDollarIcon: CurrencyDollarIcon,
  CurrencyEuroIcon: CurrencyEuroIcon,
  CurrencyPoundIcon: CurrencyPoundIcon,
  CurrencyRupeeIcon: CurrencyRupeeIcon,
  CurrencyYenIcon: CurrencyYenIcon,
  CursorClickIcon: CursorClickIcon,
  DatabaseIcon: DatabaseIcon,
  DesktopComputerIcon: DesktopComputerIcon,
  DeviceMobileIcon: DeviceMobileIcon,
  DeviceTabletIcon: DeviceTabletIcon,
  DocumentAddIcon: DocumentAddIcon,
  DocumentDownloadIcon: DocumentDownloadIcon,
  DocumentDuplicateIcon: DocumentDuplicateIcon,
  DocumentIcon: DocumentIcon,
  DocumentRemoveIcon: DocumentRemoveIcon,
  DocumentReportIcon: DocumentReportIcon,
  DocumentSearchIcon: DocumentSearchIcon,
  DocumentTextIcon: DocumentTextIcon,
  DotsCircleHorizontalIcon: DotsCircleHorizontalIcon,
  DotsHorizontalIcon: DotsHorizontalIcon,
  DotsVerticalIcon: DotsVerticalIcon,
  DownloadIcon: DownloadIcon,
  DuplicateIcon: DuplicateIcon,
  EmojiHappyIcon: EmojiHappyIcon,
  EmojiSadIcon: EmojiSadIcon,
  ExclamationCircleIcon: ExclamationCircleIcon,
  ExclamationIcon: ExclamationIcon,
  ExternalLinkIcon: ExternalLinkIcon,
  EyeIcon: EyeIcon,
  EyeOffIcon: EyeOffIcon,
  FastForwardIcon: FastForwardIcon,
  FilmIcon: FilmIcon,
  FilterIcon: FilterIcon,
  FingerPrintIcon: FingerPrintIcon,
  FireIcon: FireIcon,
  FlagIcon: FlagIcon,
  FolderAddIcon: FolderAddIcon,
  FolderDownloadIcon: FolderDownloadIcon,
  FolderIcon: FolderIcon,
  FolderOpenIcon: FolderOpenIcon,
  FolderRemoveIcon: FolderRemoveIcon,
  GiftIcon: GiftIcon,
  GlobeAltIcon: GlobeAltIcon,
  GlobeIcon: GlobeIcon,
  HandIcon: HandIcon,
  HashtagIcon: HashtagIcon,
  HeartIcon: HeartIcon,
  HomeIcon: HomeIcon,
  IdentificationIcon: IdentificationIcon,
  InboxIcon: InboxIcon,
  InboxInIcon: InboxInIcon,
  InformationCircleIcon: InformationCircleIcon,
  KeyIcon: KeyIcon,
  LibraryIcon: LibraryIcon,
  LightBulbIcon: LightBulbIcon,
  LightningBoltIcon: LightningBoltIcon,
  LinkIcon: LinkIcon,
  LocationMarkerIcon: LocationMarkerIcon,
  LockClosedIcon: LockClosedIcon,
  LockOpenIcon: LockOpenIcon,
  LoginIcon: LoginIcon,
  LogoutIcon: LogoutIcon,
  MailIcon: MailIcon,
  MailOpenIcon: MailOpenIcon,
  MapIcon: MapIcon,
  MenuAlt1Icon: MenuAlt1Icon,
  MenuAlt2Icon: MenuAlt2Icon,
  MenuAlt3Icon: MenuAlt3Icon,
  MenuAlt4Icon: MenuAlt4Icon,
  MenuIcon: MenuIcon,
  MicrophoneIcon: MicrophoneIcon,
  MinusCircleIcon: MinusCircleIcon,
  MinusIcon: MinusIcon,
  MinusSmIcon: MinusSmIcon,
  MoonIcon: MoonIcon,
  MusicNoteIcon: MusicNoteIcon,
  NewspaperIcon: NewspaperIcon,
  OfficeBuildingIcon: OfficeBuildingIcon,
  PaperAirplaneIcon: PaperAirplaneIcon,
  PaperClipIcon: PaperClipIcon,
  PauseIcon: PauseIcon,
  PencilAltIcon: PencilAltIcon,
  PencilIcon: PencilIcon,
  PhoneIcon: PhoneIcon,
  PhoneIncomingIcon: PhoneIncomingIcon,
  PhoneMissedCallIcon: PhoneMissedCallIcon,
  PhoneOutgoingIcon: PhoneOutgoingIcon,
  PhotographIcon: PhotographIcon,
  PlayIcon: PlayIcon,
  PlusCircleIcon: PlusCircleIcon,
  PlusIcon: PlusIcon,
  PlusSmIcon: PlusSmIcon,
  PresentationChartBarIcon: PresentationChartBarIcon,
  PresentationChartLineIcon: PresentationChartLineIcon,
  PrinterIcon: PrinterIcon,
  PuzzleIcon: PuzzleIcon,
  QrcodeIcon: QrcodeIcon,
  QuestionMarkCircleIcon: QuestionMarkCircleIcon,
  ReceiptRefundIcon: ReceiptRefundIcon,
  ReceiptTaxIcon: ReceiptTaxIcon,
  RefreshIcon: RefreshIcon,
  ReplyIcon: ReplyIcon,
  RewindIcon: RewindIcon,
  RssIcon: RssIcon,
  SaveAsIcon: SaveAsIcon,
  SaveIcon: SaveIcon,
  ScaleIcon: ScaleIcon,
  ScissorsIcon: ScissorsIcon,
  SearchCircleIcon: SearchCircleIcon,
  SearchIcon: SearchIcon,
  SelectorIcon: SelectorIcon,
  ServerIcon: ServerIcon,
  ShareIcon: ShareIcon,
  ShieldCheckIcon: ShieldCheckIcon,
  ShieldExclamationIcon: ShieldExclamationIcon,
  ShoppingBagIcon: ShoppingBagIcon,
  ShoppingCartIcon: ShoppingCartIcon,
  SortAscendingIcon: SortAscendingIcon,
  SortDescendingIcon: SortDescendingIcon,
  SparklesIcon: SparklesIcon,
  SpeakerphoneIcon: SpeakerphoneIcon,
  StarIcon: StarIcon,
  StatusOfflineIcon: StatusOfflineIcon,
  StatusOnlineIcon: StatusOnlineIcon,
  StopIcon: StopIcon,
  SunIcon: SunIcon,
  SupportIcon: SupportIcon,
  SwitchHorizontalIcon: SwitchHorizontalIcon,
  SwitchVerticalIcon: SwitchVerticalIcon,
  TableIcon: TableIcon,
  TagIcon: TagIcon,
  TemplateIcon: TemplateIcon,
  TerminalIcon: TerminalIcon,
  ThumbDownIcon: ThumbDownIcon,
  ThumbUpIcon: ThumbUpIcon,
  TicketIcon: TicketIcon,
  TranslateIcon: TranslateIcon,
  TrashIcon: TrashIcon,
  TrendingDownIcon: TrendingDownIcon,
  TrendingUpIcon: TrendingUpIcon,
  TruckIcon: TruckIcon,
  UploadIcon: UploadIcon,
  UserAddIcon: UserAddIcon,
  UserCircleIcon: UserCircleIcon,
  UserGroupIcon: UserGroupIcon,
  UserIcon: UserIcon,
  UserRemoveIcon: UserRemoveIcon,
  UsersIcon: UsersIcon,
  VariableIcon: VariableIcon,
  VideoCameraIcon: VideoCameraIcon,
  ViewBoardsIcon: ViewBoardsIcon,
  ViewGridAddIcon: ViewGridAddIcon,
  ViewGridIcon: ViewGridIcon,
  ViewListIcon: ViewListIcon,
  VolumeOffIcon: VolumeOffIcon,
  VolumeUpIcon: VolumeUpIcon,
  WifiIcon: WifiIcon,
  XCircleIcon: XCircleIcon,
  XIcon: XIcon,
  ZoomInIcon: ZoomInIcon,
  ZoomOutIcon: ZoomOutIcon
};

var AcademicCapIcon$1 = {};

var AdjustmentsIcon$1 = {};

var AnnotationIcon$1 = {};

var ArchiveIcon$1 = {};

var ArrowCircleDownIcon$1 = {};

var ArrowCircleLeftIcon$1 = {};

var ArrowCircleRightIcon$1 = {};

var ArrowCircleUpIcon$1 = {};

var ArrowDownIcon$1 = {};

var ArrowLeftIcon$1 = {};

var ArrowNarrowDownIcon$1 = {};

var ArrowNarrowLeftIcon$1 = {};

var ArrowNarrowRightIcon$1 = {};

var ArrowNarrowUpIcon$1 = {};

var ArrowRightIcon$1 = {};

var ArrowSmDownIcon$1 = {};

var ArrowSmLeftIcon$1 = {};

var ArrowSmRightIcon$1 = {};

var ArrowSmUpIcon$1 = {};

var ArrowUpIcon$1 = {};

var ArrowsExpandIcon$1 = {};

var AtSymbolIcon$1 = {};

var BackspaceIcon$1 = {};

var BadgeCheckIcon$1 = {};

var BanIcon$1 = {};

var BeakerIcon$1 = {};

var BellIcon$1 = {};

var BookOpenIcon$1 = {};

var BookmarkAltIcon$1 = {};

var BookmarkIcon$1 = {};

var BriefcaseIcon$1 = {};

var CakeIcon$1 = {};

var CalculatorIcon$1 = {};

var CalendarIcon$1 = {};

var CameraIcon$1 = {};

var CashIcon$1 = {};

var ChartBarIcon$1 = {};

var ChartPieIcon$1 = {};

var ChartSquareBarIcon$1 = {};

var ChatAlt2Icon$1 = {};

var ChatAltIcon$1 = {};

var ChatIcon$1 = {};

var CheckCircleIcon$1 = {};

var CheckIcon$1 = {};

var ChevronDoubleDownIcon$1 = {};

var ChevronDoubleLeftIcon$1 = {};

var ChevronDoubleRightIcon$1 = {};

var ChevronDoubleUpIcon$1 = {};

var ChevronDownIcon$1 = {};

var ChevronLeftIcon$1 = {};

var ChevronRightIcon$1 = {};

var ChevronUpIcon$1 = {};

var ChipIcon$1 = {};

var ClipboardCheckIcon$1 = {};

var ClipboardCopyIcon$1 = {};

var ClipboardIcon$1 = {};

var ClipboardListIcon$1 = {};

var ClockIcon$1 = {};

var CloudDownloadIcon$1 = {};

var CloudIcon$1 = {};

var CloudUploadIcon$1 = {};

var CodeIcon$1 = {};

var CogIcon$1 = {};

var CollectionIcon$1 = {};

var ColorSwatchIcon$1 = {};

var CreditCardIcon$1 = {};

var CubeIcon$1 = {};

var CubeTransparentIcon$1 = {};

var CurrencyBangladeshiIcon$1 = {};

var CurrencyDollarIcon$1 = {};

var CurrencyEuroIcon$1 = {};

var CurrencyPoundIcon$1 = {};

var CurrencyRupeeIcon$1 = {};

var CurrencyYenIcon$1 = {};

var CursorClickIcon$1 = {};

var DatabaseIcon$1 = {};

var DesktopComputerIcon$1 = {};

var DeviceMobileIcon$1 = {};

var DeviceTabletIcon$1 = {};

var DocumentAddIcon$1 = {};

var DocumentDownloadIcon$1 = {};

var DocumentDuplicateIcon$1 = {};

var DocumentIcon$1 = {};

var DocumentRemoveIcon$1 = {};

var DocumentReportIcon$1 = {};

var DocumentSearchIcon$1 = {};

var DocumentTextIcon$1 = {};

var DotsCircleHorizontalIcon$1 = {};

var DotsHorizontalIcon$1 = {};

var DotsVerticalIcon$1 = {};

var DownloadIcon$1 = {};

var DuplicateIcon$1 = {};

var EmojiHappyIcon$1 = {};

var EmojiSadIcon$1 = {};

var ExclamationCircleIcon$1 = {};

var ExclamationIcon$1 = {};

var ExternalLinkIcon$1 = {};

var EyeIcon$1 = {};

var EyeOffIcon$1 = {};

var FastForwardIcon$1 = {};

var FilmIcon$1 = {};

var FilterIcon$1 = {};

var FingerPrintIcon$1 = {};

var FireIcon$1 = {};

var FlagIcon$1 = {};

var FolderAddIcon$1 = {};

var FolderDownloadIcon$1 = {};

var FolderIcon$1 = {};

var FolderOpenIcon$1 = {};

var FolderRemoveIcon$1 = {};

var GiftIcon$1 = {};

var GlobeAltIcon$1 = {};

var GlobeIcon$1 = {};

var HandIcon$1 = {};

var HashtagIcon$1 = {};

var HeartIcon$1 = {};

var HomeIcon$1 = {};

var IdentificationIcon$1 = {};

var InboxIcon$1 = {};

var InboxInIcon$1 = {};

var InformationCircleIcon$1 = {};

var KeyIcon$1 = {};

var LibraryIcon$1 = {};

var LightBulbIcon$1 = {};

var LightningBoltIcon$1 = {};

var LinkIcon$1 = {};

var LocationMarkerIcon$1 = {};

var LockClosedIcon$1 = {};

var LockOpenIcon$1 = {};

var LoginIcon$1 = {};

var LogoutIcon$1 = {};

var MailIcon$1 = {};

var MailOpenIcon$1 = {};

var MapIcon$1 = {};

var MenuAlt1Icon$1 = {};

var MenuAlt2Icon$1 = {};

var MenuAlt3Icon$1 = {};

var MenuAlt4Icon$1 = {};

var MenuIcon$1 = {};

var MicrophoneIcon$1 = {};

var MinusCircleIcon$1 = {};

var MinusIcon$1 = {};

var MinusSmIcon$1 = {};

var MoonIcon$1 = {};

var MusicNoteIcon$1 = {};

var NewspaperIcon$1 = {};

var OfficeBuildingIcon$1 = {};

var PaperAirplaneIcon$1 = {};

var PaperClipIcon$1 = {};

var PauseIcon$1 = {};

var PencilAltIcon$1 = {};

var PencilIcon$1 = {};

var PhoneIcon$1 = {};

var PhoneIncomingIcon$1 = {};

var PhoneMissedCallIcon$1 = {};

var PhoneOutgoingIcon$1 = {};

var PhotographIcon$1 = {};

var PlayIcon$1 = {};

var PlusCircleIcon$1 = {};

var PlusIcon$1 = {};

var PlusSmIcon$1 = {};

var PresentationChartBarIcon$1 = {};

var PresentationChartLineIcon$1 = {};

var PrinterIcon$1 = {};

var PuzzleIcon$1 = {};

var QrcodeIcon$1 = {};

var QuestionMarkCircleIcon$1 = {};

var ReceiptRefundIcon$1 = {};

var ReceiptTaxIcon$1 = {};

var RefreshIcon$1 = {};

var ReplyIcon$1 = {};

var RewindIcon$1 = {};

var RssIcon$1 = {};

var SaveAsIcon$1 = {};

var SaveIcon$1 = {};

var ScaleIcon$1 = {};

var ScissorsIcon$1 = {};

var SearchCircleIcon$1 = {};

var SearchIcon$1 = {};

var SelectorIcon$1 = {};

var ServerIcon$1 = {};

var ShareIcon$1 = {};

var ShieldCheckIcon$1 = {};

var ShieldExclamationIcon$1 = {};

var ShoppingBagIcon$1 = {};

var ShoppingCartIcon$1 = {};

var SortAscendingIcon$1 = {};

var SortDescendingIcon$1 = {};

var SparklesIcon$1 = {};

var SpeakerphoneIcon$1 = {};

var StarIcon$1 = {};

var StatusOfflineIcon$1 = {};

var StatusOnlineIcon$1 = {};

var StopIcon$1 = {};

var SunIcon$1 = {};

var SupportIcon$1 = {};

var SwitchHorizontalIcon$1 = {};

var SwitchVerticalIcon$1 = {};

var TableIcon$1 = {};

var TagIcon$1 = {};

var TemplateIcon$1 = {};

var TerminalIcon$1 = {};

var ThumbDownIcon$1 = {};

var ThumbUpIcon$1 = {};

var TicketIcon$1 = {};

var TranslateIcon$1 = {};

var TrashIcon$1 = {};

var TrendingDownIcon$1 = {};

var TrendingUpIcon$1 = {};

var TruckIcon$1 = {};

var UploadIcon$1 = {};

var UserAddIcon$1 = {};

var UserCircleIcon$1 = {};

var UserGroupIcon$1 = {};

var UserIcon$1 = {};

var UserRemoveIcon$1 = {};

var UsersIcon$1 = {};

var VariableIcon$1 = {};

var VideoCameraIcon$1 = {};

var ViewBoardsIcon$1 = {};

var ViewGridAddIcon$1 = {};

var ViewGridIcon$1 = {};

var ViewListIcon$1 = {};

var VolumeOffIcon$1 = {};

var VolumeUpIcon$1 = {};

var WifiIcon$1 = {};

var XCircleIcon$1 = {};

var XIcon$1 = {};

var ZoomInIcon$1 = {};

var ZoomOutIcon$1 = {};

var Outline = {
  AcademicCapIcon: AcademicCapIcon$1,
  AdjustmentsIcon: AdjustmentsIcon$1,
  AnnotationIcon: AnnotationIcon$1,
  ArchiveIcon: ArchiveIcon$1,
  ArrowCircleDownIcon: ArrowCircleDownIcon$1,
  ArrowCircleLeftIcon: ArrowCircleLeftIcon$1,
  ArrowCircleRightIcon: ArrowCircleRightIcon$1,
  ArrowCircleUpIcon: ArrowCircleUpIcon$1,
  ArrowDownIcon: ArrowDownIcon$1,
  ArrowLeftIcon: ArrowLeftIcon$1,
  ArrowNarrowDownIcon: ArrowNarrowDownIcon$1,
  ArrowNarrowLeftIcon: ArrowNarrowLeftIcon$1,
  ArrowNarrowRightIcon: ArrowNarrowRightIcon$1,
  ArrowNarrowUpIcon: ArrowNarrowUpIcon$1,
  ArrowRightIcon: ArrowRightIcon$1,
  ArrowSmDownIcon: ArrowSmDownIcon$1,
  ArrowSmLeftIcon: ArrowSmLeftIcon$1,
  ArrowSmRightIcon: ArrowSmRightIcon$1,
  ArrowSmUpIcon: ArrowSmUpIcon$1,
  ArrowUpIcon: ArrowUpIcon$1,
  ArrowsExpandIcon: ArrowsExpandIcon$1,
  AtSymbolIcon: AtSymbolIcon$1,
  BackspaceIcon: BackspaceIcon$1,
  BadgeCheckIcon: BadgeCheckIcon$1,
  BanIcon: BanIcon$1,
  BeakerIcon: BeakerIcon$1,
  BellIcon: BellIcon$1,
  BookOpenIcon: BookOpenIcon$1,
  BookmarkAltIcon: BookmarkAltIcon$1,
  BookmarkIcon: BookmarkIcon$1,
  BriefcaseIcon: BriefcaseIcon$1,
  CakeIcon: CakeIcon$1,
  CalculatorIcon: CalculatorIcon$1,
  CalendarIcon: CalendarIcon$1,
  CameraIcon: CameraIcon$1,
  CashIcon: CashIcon$1,
  ChartBarIcon: ChartBarIcon$1,
  ChartPieIcon: ChartPieIcon$1,
  ChartSquareBarIcon: ChartSquareBarIcon$1,
  ChatAlt2Icon: ChatAlt2Icon$1,
  ChatAltIcon: ChatAltIcon$1,
  ChatIcon: ChatIcon$1,
  CheckCircleIcon: CheckCircleIcon$1,
  CheckIcon: CheckIcon$1,
  ChevronDoubleDownIcon: ChevronDoubleDownIcon$1,
  ChevronDoubleLeftIcon: ChevronDoubleLeftIcon$1,
  ChevronDoubleRightIcon: ChevronDoubleRightIcon$1,
  ChevronDoubleUpIcon: ChevronDoubleUpIcon$1,
  ChevronDownIcon: ChevronDownIcon$1,
  ChevronLeftIcon: ChevronLeftIcon$1,
  ChevronRightIcon: ChevronRightIcon$1,
  ChevronUpIcon: ChevronUpIcon$1,
  ChipIcon: ChipIcon$1,
  ClipboardCheckIcon: ClipboardCheckIcon$1,
  ClipboardCopyIcon: ClipboardCopyIcon$1,
  ClipboardIcon: ClipboardIcon$1,
  ClipboardListIcon: ClipboardListIcon$1,
  ClockIcon: ClockIcon$1,
  CloudDownloadIcon: CloudDownloadIcon$1,
  CloudIcon: CloudIcon$1,
  CloudUploadIcon: CloudUploadIcon$1,
  CodeIcon: CodeIcon$1,
  CogIcon: CogIcon$1,
  CollectionIcon: CollectionIcon$1,
  ColorSwatchIcon: ColorSwatchIcon$1,
  CreditCardIcon: CreditCardIcon$1,
  CubeIcon: CubeIcon$1,
  CubeTransparentIcon: CubeTransparentIcon$1,
  CurrencyBangladeshiIcon: CurrencyBangladeshiIcon$1,
  CurrencyDollarIcon: CurrencyDollarIcon$1,
  CurrencyEuroIcon: CurrencyEuroIcon$1,
  CurrencyPoundIcon: CurrencyPoundIcon$1,
  CurrencyRupeeIcon: CurrencyRupeeIcon$1,
  CurrencyYenIcon: CurrencyYenIcon$1,
  CursorClickIcon: CursorClickIcon$1,
  DatabaseIcon: DatabaseIcon$1,
  DesktopComputerIcon: DesktopComputerIcon$1,
  DeviceMobileIcon: DeviceMobileIcon$1,
  DeviceTabletIcon: DeviceTabletIcon$1,
  DocumentAddIcon: DocumentAddIcon$1,
  DocumentDownloadIcon: DocumentDownloadIcon$1,
  DocumentDuplicateIcon: DocumentDuplicateIcon$1,
  DocumentIcon: DocumentIcon$1,
  DocumentRemoveIcon: DocumentRemoveIcon$1,
  DocumentReportIcon: DocumentReportIcon$1,
  DocumentSearchIcon: DocumentSearchIcon$1,
  DocumentTextIcon: DocumentTextIcon$1,
  DotsCircleHorizontalIcon: DotsCircleHorizontalIcon$1,
  DotsHorizontalIcon: DotsHorizontalIcon$1,
  DotsVerticalIcon: DotsVerticalIcon$1,
  DownloadIcon: DownloadIcon$1,
  DuplicateIcon: DuplicateIcon$1,
  EmojiHappyIcon: EmojiHappyIcon$1,
  EmojiSadIcon: EmojiSadIcon$1,
  ExclamationCircleIcon: ExclamationCircleIcon$1,
  ExclamationIcon: ExclamationIcon$1,
  ExternalLinkIcon: ExternalLinkIcon$1,
  EyeIcon: EyeIcon$1,
  EyeOffIcon: EyeOffIcon$1,
  FastForwardIcon: FastForwardIcon$1,
  FilmIcon: FilmIcon$1,
  FilterIcon: FilterIcon$1,
  FingerPrintIcon: FingerPrintIcon$1,
  FireIcon: FireIcon$1,
  FlagIcon: FlagIcon$1,
  FolderAddIcon: FolderAddIcon$1,
  FolderDownloadIcon: FolderDownloadIcon$1,
  FolderIcon: FolderIcon$1,
  FolderOpenIcon: FolderOpenIcon$1,
  FolderRemoveIcon: FolderRemoveIcon$1,
  GiftIcon: GiftIcon$1,
  GlobeAltIcon: GlobeAltIcon$1,
  GlobeIcon: GlobeIcon$1,
  HandIcon: HandIcon$1,
  HashtagIcon: HashtagIcon$1,
  HeartIcon: HeartIcon$1,
  HomeIcon: HomeIcon$1,
  IdentificationIcon: IdentificationIcon$1,
  InboxIcon: InboxIcon$1,
  InboxInIcon: InboxInIcon$1,
  InformationCircleIcon: InformationCircleIcon$1,
  KeyIcon: KeyIcon$1,
  LibraryIcon: LibraryIcon$1,
  LightBulbIcon: LightBulbIcon$1,
  LightningBoltIcon: LightningBoltIcon$1,
  LinkIcon: LinkIcon$1,
  LocationMarkerIcon: LocationMarkerIcon$1,
  LockClosedIcon: LockClosedIcon$1,
  LockOpenIcon: LockOpenIcon$1,
  LoginIcon: LoginIcon$1,
  LogoutIcon: LogoutIcon$1,
  MailIcon: MailIcon$1,
  MailOpenIcon: MailOpenIcon$1,
  MapIcon: MapIcon$1,
  MenuAlt1Icon: MenuAlt1Icon$1,
  MenuAlt2Icon: MenuAlt2Icon$1,
  MenuAlt3Icon: MenuAlt3Icon$1,
  MenuAlt4Icon: MenuAlt4Icon$1,
  MenuIcon: MenuIcon$1,
  MicrophoneIcon: MicrophoneIcon$1,
  MinusCircleIcon: MinusCircleIcon$1,
  MinusIcon: MinusIcon$1,
  MinusSmIcon: MinusSmIcon$1,
  MoonIcon: MoonIcon$1,
  MusicNoteIcon: MusicNoteIcon$1,
  NewspaperIcon: NewspaperIcon$1,
  OfficeBuildingIcon: OfficeBuildingIcon$1,
  PaperAirplaneIcon: PaperAirplaneIcon$1,
  PaperClipIcon: PaperClipIcon$1,
  PauseIcon: PauseIcon$1,
  PencilAltIcon: PencilAltIcon$1,
  PencilIcon: PencilIcon$1,
  PhoneIcon: PhoneIcon$1,
  PhoneIncomingIcon: PhoneIncomingIcon$1,
  PhoneMissedCallIcon: PhoneMissedCallIcon$1,
  PhoneOutgoingIcon: PhoneOutgoingIcon$1,
  PhotographIcon: PhotographIcon$1,
  PlayIcon: PlayIcon$1,
  PlusCircleIcon: PlusCircleIcon$1,
  PlusIcon: PlusIcon$1,
  PlusSmIcon: PlusSmIcon$1,
  PresentationChartBarIcon: PresentationChartBarIcon$1,
  PresentationChartLineIcon: PresentationChartLineIcon$1,
  PrinterIcon: PrinterIcon$1,
  PuzzleIcon: PuzzleIcon$1,
  QrcodeIcon: QrcodeIcon$1,
  QuestionMarkCircleIcon: QuestionMarkCircleIcon$1,
  ReceiptRefundIcon: ReceiptRefundIcon$1,
  ReceiptTaxIcon: ReceiptTaxIcon$1,
  RefreshIcon: RefreshIcon$1,
  ReplyIcon: ReplyIcon$1,
  RewindIcon: RewindIcon$1,
  RssIcon: RssIcon$1,
  SaveAsIcon: SaveAsIcon$1,
  SaveIcon: SaveIcon$1,
  ScaleIcon: ScaleIcon$1,
  ScissorsIcon: ScissorsIcon$1,
  SearchCircleIcon: SearchCircleIcon$1,
  SearchIcon: SearchIcon$1,
  SelectorIcon: SelectorIcon$1,
  ServerIcon: ServerIcon$1,
  ShareIcon: ShareIcon$1,
  ShieldCheckIcon: ShieldCheckIcon$1,
  ShieldExclamationIcon: ShieldExclamationIcon$1,
  ShoppingBagIcon: ShoppingBagIcon$1,
  ShoppingCartIcon: ShoppingCartIcon$1,
  SortAscendingIcon: SortAscendingIcon$1,
  SortDescendingIcon: SortDescendingIcon$1,
  SparklesIcon: SparklesIcon$1,
  SpeakerphoneIcon: SpeakerphoneIcon$1,
  StarIcon: StarIcon$1,
  StatusOfflineIcon: StatusOfflineIcon$1,
  StatusOnlineIcon: StatusOnlineIcon$1,
  StopIcon: StopIcon$1,
  SunIcon: SunIcon$1,
  SupportIcon: SupportIcon$1,
  SwitchHorizontalIcon: SwitchHorizontalIcon$1,
  SwitchVerticalIcon: SwitchVerticalIcon$1,
  TableIcon: TableIcon$1,
  TagIcon: TagIcon$1,
  TemplateIcon: TemplateIcon$1,
  TerminalIcon: TerminalIcon$1,
  ThumbDownIcon: ThumbDownIcon$1,
  ThumbUpIcon: ThumbUpIcon$1,
  TicketIcon: TicketIcon$1,
  TranslateIcon: TranslateIcon$1,
  TrashIcon: TrashIcon$1,
  TrendingDownIcon: TrendingDownIcon$1,
  TrendingUpIcon: TrendingUpIcon$1,
  TruckIcon: TruckIcon$1,
  UploadIcon: UploadIcon$1,
  UserAddIcon: UserAddIcon$1,
  UserCircleIcon: UserCircleIcon$1,
  UserGroupIcon: UserGroupIcon$1,
  UserIcon: UserIcon$1,
  UserRemoveIcon: UserRemoveIcon$1,
  UsersIcon: UsersIcon$1,
  VariableIcon: VariableIcon$1,
  VideoCameraIcon: VideoCameraIcon$1,
  ViewBoardsIcon: ViewBoardsIcon$1,
  ViewGridAddIcon: ViewGridAddIcon$1,
  ViewGridIcon: ViewGridIcon$1,
  ViewListIcon: ViewListIcon$1,
  VolumeOffIcon: VolumeOffIcon$1,
  VolumeUpIcon: VolumeUpIcon$1,
  WifiIcon: WifiIcon$1,
  XCircleIcon: XCircleIcon$1,
  XIcon: XIcon$1,
  ZoomInIcon: ZoomInIcon$1,
  ZoomOutIcon: ZoomOutIcon$1
};

export {
  Solid ,
  Outline ,
  
}
/* No side effect */
